### ISSUE TITLE
Error "error configuring application listener of class com.sitewhere.web.ShutdownListener" during deploy Sitewhere with Tomcat 8

### ISSUE THREAD

**Issue by anhdenday** [sitewhere/sitewhere#18]
Hi All

I am new to Sitewhere, I just downloaded sitewhere project and deploy to tomcat for debugging. But when I run it on tomcat, it's appear the error below. I am using the latest version of sitewhere 1.5 Please check it out for me. Below is error.

SEVERE: Error configuring application listener of class com.sitewhere.web.ShutdownListener
java.lang.ClassNotFoundException: com.sitewhere.web.ShutdownListener
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1333)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1167)
	at org.apache.catalina.core.DefaultInstanceManager.loadClass(DefaultInstanceManager.java:520)
	at org.apache.catalina.core.DefaultInstanceManager.loadClassMaybePrivileged(DefaultInstanceManager.java:501)
	at org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:120)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4734)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5255)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1408)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1398)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Thanks you so much

**Comment by derekadams** [comment]
Did you build the system from source or deploy one of the packaged distributions from [the downloads page](http://www.sitewhere.org/downloads/)? If building from source, make sure you have run the following to properly build the server:

```
mvn clean install
mvn -P buildServer install
```

**Comment by anhdenday** [comment]
Dear Derekadams,
I just clone the source code from github and building from source code and also build with maven, after building successful with maven command: "mvn clean install -Dmaven.test.skip=true" then I start tomcat inside eclipse. Above error appear during i start sitewhere web with tomcat :) I will try with "mvn -P buildServer install" command before start tomcat and will let you know the result :+1:

**Comment by anhdenday** [comment]
Dear Derekadams,

After running "mvn -P buildServer install" command, then I continue to start tomcat inside eclipse, another exception is throw as below.

SEVERE: Servlet.service() for servlet [mvc] in context with path [/sitewhere] threw exception [Request processing failed; nested exception is java.lang.NullPointerException] with root cause
java.lang.NullPointerException
	at com.sitewhere.web.mvc.SiteWhereController.login(SiteWhereController.java:81)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.web.bind.annotation.support.HandlerMethodInvoker.invokeHandlerMethod(HandlerMethodInvoker.java:176)
	at org.springframework.web.servlet.mvc.annotation.AnnotationMethodHandlerAdapter.invokeHandlerMethod(AnnotationMethodHandlerAdapter.java:440)
	at org.springframework.web.servlet.mvc.annotation.AnnotationMethodHandlerAdapter.handle(AnnotationMethodHandlerAdapter.java:428)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:919)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:851)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:953)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:844)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:829)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)

I am running on Mac OS X. I already install MongoDB and mosquitto on my Mac

Thanks

**Comment by derekadams** [comment]
When you say you are running SiteWhere on Tomcat in Eclipse, is that an embedded Tomcat instance? If so, that's an untested configuration. The output of the "buildServer" command is a standalone Tomcat installation with the SiteWhere configuration files and WAR already in place (see deploy folder under the root for sitewhere-server-1.5.0.zip or tar.gz). You may be able to copy the contents of the conf/sitewhere directory from the distribution and get it to work in Eclipse, but we recommend running the system from the packaged archive.

**Comment by anhdenday** [comment]
Yes, my purpose is debugging sitewhere in eclipse directly. So that is why I start sitewhere inside eclipse. If I follow you to run tomcat from sitewhere-server-1.5.0.zip or tar.gz extract file it's ok. But if i run tomcat inside eclipse it's still error. I will check the configuration more deeply!
![sitewhere_start_tomcat](https://cloud.githubusercontent.com/assets/6926208/12318032/7702147a-bac9-11e5-8685-09084cf7228f.png)

**Comment by derekadams** [comment]
One option is to connect to the external SiteWhere/Tomcat instance remotely from Eclipse. That will still allow you to set breakpoints in the code just as if it were running locally (it's the method we use to debug). If you edit the command near the bottom of the startup.bat file (or similarly in startup.sh) as shown below:

```
call "%EXECUTABLE%" jpda start %CMD_LINE_ARGS%
```

.. then connect from Eclipse with the following Remote Java Application settings..

![image](https://cloud.githubusercontent.com/assets/338921/12338401/60e176fe-badd-11e5-9836-f4ca8faaa075.png)

The debugger should connect and allow you to debug the code.

Hope that helps!

**Comment by anhdenday** [comment]
That's great, I was  Remote debugging of Tomcat using Eclipse successful. Thanks you so much

**Comment by sameerbetageri10** [comment]
unable to load the adminiistartive console of the sitewhere. I have set up mongodb and mosquitto mqtt server but stiill unable startup the home page of sitewhere

**Comment by anhdenday** [comment]
Sitewhere now using Spring Boot, I think you should open another issue and describle more detail your issue!

**Comment by sameerbetageri10** [comment]
@anhdenday can u provide installation procedure for installing sitewhere inn win7 using mosquitto mqtt...............i have tried installing using the same way as using hive mq ended up in a dead end

**Comment by sameerbetageri10** [comment]
unable to run sitewhere admin console at http://localhost:8080/sitewhere

**Comment by anhdenday** [comment]
You just want to install or you want to debug from the IDE like Eclipse or IntellijUDEA?

**Comment by sameerbetageri10** [comment]
Sitewhere installation problem #45

https://github.com/sitewhere/sitewhere/issues/45

**Comment by sameerbetageri10** [comment]
i just want to install sitewhere....iam using the mongodb and mosquitto at
1883 port bith are up n running....started sitewhere server....stil unable
to open sitewhere admin

Iam not using eclipse IDE

**Comment by sameerbetageri10** [comment]
i have followed the innstallation video on youtube ....followed those steps

**Comment by anhdenday** [comment]
The step like this: 
1- Install JDK 8
2- Install MongoDB 
3- Install Message Broker (like HiveMQ or Mosquitto)
4- Run sitewhere like tutorial at sitewhere page
cd /opt
wget https://s3.amazonaws.com/sitewhere/sitewhere-server-1.7.0.tgz
tar -zxvf sitewhere-server-1.7.0.tgz
mv sitewhere-server-1.7.0 /opt/sitewhere
export SITEWHERE_HOME=/opt/sitewhere
cd /opt/sitewhere/bin
sh startup.sh
Brgs

**Comment by anhdenday** [comment]
In the window, I just run inside the IDE like IntelliJ IDEA for debugging in my local. 
To deploy on the server i am usually using Ubuntu.
I never install sitewhere server on window before, just run directly from the source code by using IDE like Eclipse or IntelliJ . But the step is the same.

1- Install JDK 8
2- Install MongoDB 
3- Install Message Broker (like HiveMQ or Mosquitto)
4- Run sitewhere on IDE

**Comment by anhdenday** [comment]
The admin console should be: http://localhost:8080/sitewhere/admin/

**Comment by sameerbetageri10** [comment]
can u provide link for steps to run from ide eclipse

**Comment by anhdenday** [comment]
Sitewhere 1.7 had problem with spring boot during running on eclipse. I've changed to use IntelliJ and it's ok. Following above step I've mentioned before and refer this issue #39 .
Hope this help
