### ISSUE TITLE
Accessing specifications on new tenant gives invalid asset reference

### ISSUE THREAD

**Issue by derekadams** [sitewhere/sitewhere#219]
Starting with a clean system, add a new tenant and start it to initialize the data. Open the device specifications list. No specifications are listed and there is an exception in the log complaining that an asset reference is not found.

{code:java}
com.sitewhere.spi.SiteWhereSystemException: Asset reference not found.
        at com.sitewhere.device.marshaling.DeviceSpecificationMarshalHelper.convert(DeviceSpecificationMarshalHelper.java:63)
        at com.sitewhere.web.rest.controllers.SpecificationsController.listDeviceSpecifications(SpecificationsController.java:276)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:222)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:814)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:737)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)

{code}

**Comment by derekadams** [comment]
From https://sitewhere.atlassian.net/browse/SITEWHERE-277
