### ISSUE TITLE
List devices error during browser sitewhere! 

### ISSUE THREAD

**Issue by anhdenday** [sitewhere/sitewhere#32]
Hi @derekadams 
I am running sitewhere 1.6 on Ubuntu. I am trying to browser the list of devices on Web Admin GUI. 
http://mysitewhereipaddress:8080/sitewhere/admin/devices/list.html
But nothing is show, I've checked on the catalina.out file it's throw an exception below. 
`21:38:26,712 ERROR [RestController] Exeception thrown during REST processing.
com.sitewhere.spi.SiteWhereException: Device references non-existent specification.
	at com.sitewhere.device.marshaling.DeviceMarshalHelper.convert(DeviceMarshalHelper.java:101)
	at com.sitewhere.web.rest.controllers.DevicesController.listDevices(DevicesController.java:433)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:222)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
`
I dont know what happen because the last time it's ok. I also check on mongodb, the data is existence with command.
> db.devices.find();  // it's show data
But it's not show in the web and the exception is throw as above. Please tell me to check it out.
Thanks you so much

**Comment by derekadams** [comment]
The problem is that the device specification used by the device has been deleted. We added a check in the REST service in 1.6.0 to prevent this from happening:

https://sitewhere.atlassian.net/browse/SITEWHERE-267

Is it possible that you have deleted a device specification directly from the database? If not, there is a condition that we are not taking care of in the delete REST method. We will take a look at it, but the general advice is not to delete device specifications unless there are no devices using them. The only way to fix the problem is to add a specification with the same UUID of the one that was deleted.

**Comment by anhdenday** [comment]
Actually I want to build another website (not admin GUI) which integrated billing, pricing for device...etc. So that I am using sitewhere java client to interact with sitewhere server. I just test CRUD but I dont remember exactly which device specification that I deleted. So I just hot fix by the way drop that database and start tomcat again. (It's only test environment so that OK). 
Thanks you for your support!

**Comment by anhdenday** [comment]
I found again the code that cause the problem. I just make a main method to test like that. After run this code, the problem above will be appear.
Below is code.

> public static void main(String[] args) throws SiteWhereException {
		ISiteWhereClient client = new SiteWhereClient("http://mysitewhere:8080/sitewhere/api/", "admin","password");
		DeviceCreateRequest request = new DeviceCreateRequest();
		request.setHardwareId("1234-freeman-4321");
		request.setSiteToken("freeman-site-token-123456");
		request.setSpecificationToken("spect-tokent-123456");
		client.createDevice(request);
		System.out.println("Create successfull");
	}

Below is exception after running this code

> DEBUG: org.springframework.web.client.RestTemplate - Created POST request for "http://mysitewhere:8080/sitewhere/api/devices"
DEBUG: org.springframework.web.client.RestTemplate - Setting request Accept header to [application/json, application/*+json]
DEBUG: org.springframework.web.client.RestTemplate - Writing [com.sitewhere.rest.model.device.request.DeviceCreateRequest@49e53c76] using [org.springframework.http.converter.json.MappingJackson2HttpMessageConverter@351d00c0]
DEBUG: org.springframework.web.client.RestTemplate - POST request for "http://123.30.50.92:8080/sitewhere/api/devices" resulted in 400 (Bad Request); invoking error handler
Exception in thread "main" com.sitewhere.spi.SiteWhereSystemException: Unknown error.
	at com.sitewhere.rest.client.SiteWhereErrorHandler.handleError(SiteWhereErrorHandler.java:53)
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:636)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:592)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:560)
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:479)
	at com.sitewhere.rest.client.SiteWhereClient.sendRest(SiteWhereClient.java:970)
	at com.sitewhere.rest.client.SiteWhereClient.createDevice(SiteWhereClient.java:369)
	at vn.vnpt.iot.m2m.web.service.impl.TestSiteWhere.main(TestSiteWhere.java:24)

After that I browser device list will appear the log as the last post. Thanks
