### ISSUE TITLE
Problem during start tenant!

### ISSUE THREAD

**Issue by anhdenday** [sitewhere/sitewhere#33]
Hi All,
I created new tenant and then start it but It appear an error.
`14:43:58,258 INFO  [QuartzScheduler] Scheduler meta-data: Quartz Scheduler (v2.2.2) '123456' with instanceId 'sitewhere'
  Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 5 threads.
  Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.

14:43:58,258 INFO  [DirectSchedulerFactory] Quartz scheduler '123456
14:43:58,258 INFO  [DirectSchedulerFactory] Quartz scheduler version: 2.2.2
14:43:58,258 INFO  [QuartzScheduleManager] QuartzScheduleManager state transitioned to STARTING.
14:43:58,258 INFO  [QuartzScheduler] Scheduler 123456_$_sitewhere started.
14:43:58,258 INFO  [QuartzScheduleManager] Updated cache with 5 schedules.
14:43:58,259 INFO  [QuartzScheduleManager] QuartzScheduleManager state transitioned to STARTED.
14:43:58,259 INFO  [SiteWhereTenantEngine] Tenant Engine: freeman state transitioned to STARTED.
14:43:58,260 INFO  [ResponseTimerFilter] Call for POST to 'http://sitewhereweb:8080/sitewhere/api/tenants/123456/engine/start' returned in 105 ms.
14:43:58,717 INFO  [ResponseTimerFilter] Call for GET to 'http://sitewhereweb:8080/sitewhere/api/users' returned in 2 ms.
14:43:58,725 INFO  [ResponseTimerFilter] Call for GET to 'http://sitewhereweb:8080/sitewhere/api/tenants/123456' returned in 5 ms.
14:43:58,732 INFO  [ResponseTimerFilter] Call for GET to 'http://sitewhereweb:8080/sitewhere/api/tenants/123456/engine/configuration/json' returned in 12 ms.` 

Thanks

**Comment by anhdenday** [comment]
Event when I removed DB and start SiteWhere Server again, It's still appearing the problem as below

> 15:36:56,708 INFO  [QuartzScheduler] Scheduler meta-data: Quartz Scheduler (v2.2.2) 'default' with instanceId 'sitewhere'
  Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 5 threads.
  Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.

**Comment by derekadams** [comment]
This looks like the normal log output. The section you posted above is the logging for the Quartz scheduler which appears to be starting normally. Are you seeing an error condition somewhere else?

**Comment by anhdenday** [comment]
Yes, it's look like the normal output but it's is bug (in my case). I describe my workflow for you.
1- I login with user "admin", and go to "Manage Users" to create new user name is "freeman"
2- After finish creating user, I go to "manage tenants" to create a tenant with tenant id is "123456" and in the field "Authorized Users" I select user is "freeman" to assign to this tenant
3- Start above tenant (and the output will appear look like normal as above even if the Quartz is NOT STARTED.)
4- Logout "admin" account then login into "freeman" account
5- Browser to "devices/spectifications and devices/devices" it's will have no data.
6- I check the log file will appear below

> 23:45:03,198 WARN  [DeviceSpecificationMarshalHelper] Device specification has reference to non-existent asset.
23:45:03,198 ERROR [RestController] Exeception thrown during REST processing.
com.sitewhere.spi.SiteWhereSystemException: Asset reference not found.
	at com.sitewhere.device.marshaling.DeviceSpecificationMarshalHelper.convert(DeviceSpecificationMarshalHelper.java:63)
	at com.sitewhere.web.rest.controllers.SpecificationsController.listDeviceSpecifications(SpecificationsController.java:276)
	at sun.reflect.GeneratedMethodAccessor262.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:222)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:814)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:737)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:969)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:860)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:845)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at com.sitewhere.web.JsonpFilter.doFilter(JsonpFilter.java:80)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at com.sitewhere.web.NoCacheFilter.doFilterInternal(NoCacheFilter.java:37)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at com.sitewhere.web.ResponseTimerFilter.doFilterInternal(ResponseTimerFilter.java:40)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at com.sitewhere.web.MethodOverrideFilter.doFilterInternal(MethodOverrideFilter.java:44)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:316)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:126)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:90)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:122)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:169)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:48)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:158)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:120)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:64)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:91)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:53)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:213)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:176)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
23:45:03,199 INFO  [ResponseTimerFilter] Call for GET to 'http://sitewhere:8080/sitewhere/api/specifications' returned in 4 ms.
23:45:03,264 INFO  [ResponseTimerFilter] Call for GET to 'http://sitewhere:8080/sitewhere/api/assets/modules/fs-devices/assets' returned in 2 ms.
Please check it out, thanks you

**Comment by derekadams** [comment]
The error you are seeing is not related to Quartz. It's used for scheduling and is starting properly based on the log output. The error message you are getting now indicates invalid data has been created for a device specification. The device specification references a non-existent asset. Is it possible that you have created data via REST services or direct manipulation of the database that would cause the specification to reference an invalid asset? For now, SiteWhere finds the bad linkage and throws an exception which is why you are not seeing anything in the admin UI. The REST services do not currently validate that the asset module/asset id combination is a valid reference when you create a device specification, so you have to be careful when adding specifications via the REST interfaces. We can look into having a fallback "invalid asset" placeholder so that the REST call does not fail even with bad data, but for now it's an error condition if the data is invalid.

**Comment by anhdenday** [comment]
Actually I reproduce 6 steps above by manually via admin UI. Not REST services. Cause the error last time at #32 that I hot fix by the way removed all database and start tomcat (sitewhere server) again so that all database will re-created again. And then I reproduce 6 steps above and see the error above.

**Comment by derekadams** [comment]
I think I know what the problem is. Are you running 1.6.0 or 1.6.1? There were bugs found in the 1.6.0 release, so we immediately put out a 1.6.1 release to address them. The one you are running in to is probably:

https://sitewhere.atlassian.net/browse/SITEWHERE-277

We are working on improving our test so that these types of bugs do not slip through in the future.

Thanks,
Derek

**Comment by anhdenday** [comment]
I think the error is cause of 1.6.0. I've just changed to 1.6.1 so that error is disappear now.
I will ignored 1.6.0 and continue with 1.6.1. Thanks
