### ISSUE TITLE
Not authorized to view information for tenant during interact witth Sitewhere Server 1.6.1 using SiteWhere Java Client!

### ISSUE THREAD

**Issue by anhdenday** [sitewhere/sitewhere#35]
Hi,
I am using sitewhere java client to interact with sitewhere server, I write a function to get the list of devices spectification. With admin credentials it is ok, but with another account it throw the SiteWhereSystemException. Below is my code: 

> public static void main(String[] args) throws SiteWhereException {
> 		
> 		ISiteWhereClient client = new SiteWhereClient("http://mysitewhereserver:8080/sitewhere/api/", "freeman","abc@123456"); // admin account is ok
> 		//list devices
> 		SearchCriteria sc = new SearchCriteria(1,5);
> 		
> 		long numberOfResults = client.listDeviceSpecifications(true, true, sc).getNumResults();
> 		
> 		System.out.println("Number of results: " + numberOfResults);
> 		
> 		List<? extends DeviceSpecification> list = client.listDeviceSpecifications(true, true, sc).getResults();
> 		
> 		for (DeviceSpecification ds: list){
> 			System.out.println("Device Specification name: "+ ds.getName());
> 		}
> }

If I run this code with admin account it's ok, but if i run with another account but full permission it's will throw with the exception: 
> Exception in thread "main" com.sitewhere.spi.SiteWhereSystemException: Not authorized to view information for tenant.
	at com.sitewhere.rest.client.SiteWhereErrorHandler.handleError(SiteWhereErrorHandler.java:50)
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:636)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:592)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:560)
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:479)
	at com.sitewhere.rest.client.SiteWhereClient.sendRest(SiteWhereClient.java:970)
	at com.sitewhere.rest.client.SiteWhereClient.listDeviceSpecifications(SiteWhereClient.java:257)
	at vn.vnpt.iot.m2m.web.service.impl.TestSiteWhere.main(TestSiteWhere.java:25)

But If i login directly in the GUI web with freeman/abc@123456 account it's still ok. Please check it 
PS: Recognizing that all tenants is started!

Thanks

**Comment by derekadams** [comment]
The constructor you are using is not the one that passes tenant auth token, so it's using the default. If you add the token for the tenant you want to access as a fourth parameter, it should work.

**Comment by anhdenday** [comment]
OK, it's my mistake. Thanks you!
