### ISSUE TITLE
Sitewhere Exception on server startup!

### ISSUE THREAD

**Issue by anhdenday** [sitewhere/sitewhere#39]
Hi @derekadams, 

I am trying to debug sitewhere 1.7 from the source code with intellij idea on the Window local. I already set JAVA_HOME and SITEWHERE_HOME on Environment Variables.. But when I run "SiteWhereWebApplication.java" it's throw an exception below.

`10:35:16,437 ERROR [SiteWhereApplication] Exception on server startup.
com.sitewhere.spi.SiteWhereException: SITEWHERE_HOME not set.
	at com.sitewhere.configuration.DefaultGlobalConfigurationResolver.getGlobalConfigurationFolder(DefaultGlobalConfigurationResolver.java:36)
	at com.sitewhere.configuration.FileSystemGlobalConfigurationResolver.getConfigurationRoot(FileSystemGlobalConfigurationResolver.java:155)
	at com.sitewhere.configuration.ConfigurationMigrationSupport.migrateProjectStructureIfNecessary(ConfigurationMigrationSupport.java:57)
	at com.sitewhere.server.SiteWhereServer.initialize(SiteWhereServer.java:752)
	at com.sitewhere.SiteWhere.start(SiteWhere.java:34)`  

Please take a look. Thanks you

**Comment by derekadams** [comment]
Try setting the variable 'sitewhere.home' rather than 'SITEWHERE_HOME'. We added the following Jira ticket to fix the problem:

https://sitewhere.atlassian.net/browse/SITEWHERE-311

Thanks,
Derek

**Comment by anhdenday** [comment]
It's still same problem even when I set the variable 'sitewhere.home'.
![5-9-2016 5-18-29 pm](https://cloud.githubusercontent.com/assets/6926208/15110304/3cc07c1a-160a-11e6-9d08-4d92c721b02b.png)

Thanks

**Comment by anhdenday** [comment]
I just tried in the Mac OSX also. The same problem here, then I tried to hard core in DefaultGlobalConfigurationResolver class.
	public static final String SITEWHERE_HOME = "/Users/freeman/Dropbox/M2M/SOURCECODE/sitewhere/sitewhere1.7.0/sitewhere";
But the problem still appear. May be there are another configuration but I dont know.
Hope to fix it out soon

**Comment by derekadams** [comment]
The SITEWHERE_HOME variable is being used to look up an environment
variable, so setting it to a path will not work. Instead, you could return
a new File object from the getGlobalConfigurationFolder() method that
points to your path. All other resolution happens relative to that folder,
so it should fix the problem. We do not have any core developers using
IntelliJ Idea, so we have not been able to replicate the environment
variable problem. It may be easier to turn on remote debugging on the
server and attach to a running instance. That is how we debug when using
Eclipse. On WIndows, you can remove the "rem" on the JPDA_OPTS line in
startup.bat to enable remote debugging.

**Comment by anhdenday** [comment]
Hi,
I am back to eclipse (STS - Spring Tool Suite), but it appear new problem of slf4j.

```
Exception in thread "main" java.lang.IllegalArgumentException: LoggerFactory is not a Logback LoggerContext but Logback is on the classpath. Either remove Logback or the competing implementation (class org.slf4j.impl.Log4jLoggerFactory loaded from file:/C:/Users/Freeman/.gradle/caches/modules-2/files-2.1/org.apache.activemq/activemq-all/5.10.0/bb376083b608a6f74e3d3c06afb92049549302c9/activemq-all-5.10.0.jar). If you are using WebLogic you will need to add 'org.slf4j' to prefer-application-packages in WEB-INF/weblogic.xml Object of class [org.slf4j.impl.Log4jLoggerFactory] must be an instance of class ch.qos.logback.classic.LoggerContext
	at org.springframework.util.Assert.isInstanceOf(Assert.java:346)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.getLoggerContext(LogbackLoggingSystem.java:223)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.getLogger(LogbackLoggingSystem.java:215)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.beforeInitialize(LogbackLoggingSystem.java:98)
	at org.springframework.boot.logging.LoggingApplicationListener.onApplicationStartedEvent(LoggingApplicationListener.java:191)
	at org.springframework.boot.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:173)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:163)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:136)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:119)
	at org.springframework.boot.context.event.EventPublishingRunListener.publishEvent(EventPublishingRunListener.java:111)
	at org.springframework.boot.context.event.EventPublishingRunListener.started(EventPublishingRunListener.java:60)
	at org.springframework.boot.SpringApplicationRunListeners.started(SpringApplicationRunListeners.java:48)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1191)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1180)
	at com.sitewhere.web.SiteWhereWebApplication.main(SiteWhereWebApplication.java:133)
```
![error](https://cloud.githubusercontent.com/assets/6926208/15142268/8ca1c526-16ce-11e6-9197-b32f6aed93cd.png)

**Comment by anhdenday** [comment]
Hi @derekadams, 

Finally I've run sitewhere on the Intelij Idea with no error on the console. I copy pre-configured of "conf" folder to SITEWHERE_HOME/conf and run with Intelij Idea with no error. But when I browser to:
http://localhost:8080/sitewhere/admin  
it's appear error message: 
```
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Fri May 13 09:58:17 ICT 2016
There was an unexpected error (type=Not Found, status=404).
/sitewhere/WEB-INF/jsp/login.jsp
```
Please take a look, thanks

**Comment by anhdenday** [comment]
Hi, 
On the Mac OSX also, If I run main method from "SiteWhereWebApplication" class it will appear the same error as above. (not worked)
But if I run with command: "gradle bootRun" it's worked.
On window if i do the same "gradle bootRun" it's will throw and exception like this, I try to fix many time with many way even I use "long path tool" but not work, I thinks it's is bug of window 10.
`Caused by: java.io.IOException: CreateProcess error=206, The filename or extension is too long
`
So temporary I am working with Mac OS.
Thanks you
