### ISSUE TITLE
Tenant State: Error

### ISSUE THREAD

**Issue by bdyz1016** [sitewhere/sitewhere#495]
java.lang.RuntimeException: Unable to create Quartz scheduler for schedule manager.
	at com.sitewhere.server.scheduling.QuartzScheduleManager.setTenant(QuartzScheduleManager.java:82) ~[sitewhere-core-1.10.0.jar!/:?]
	at com.sitewhere.server.lifecycle.TenantLifecycleComponent.startNestedComponent(TenantLifecycleComponent.java:58) ~[sitewhere-core-1.10.0.jar!/:?]
	at com.sitewhere.server.lifecycle.StartComponentLifecycleStep.execute(StartComponentLifecycleStep.java:36) ~[sitewhere-core-1.10.0.jar!/:?]
	at com.sitewhere.server.lifecycle.CompositeLifecycleStep.execute(CompositeLifecycleStep.java:76) ~[sitewhere-core-1.10.0.jar!/:?]
	at com.sitewhere.server.SiteWhereTenantEngine.start(SiteWhereTenantEngine.java:259) ~[sitewhere-core-1.10.0.jar!/:?]
	at com.sitewhere.server.lifecycle.LifecycleComponent.lifecycleStart(LifecycleComponent.java:164) [sitewhere-core-1.10.0.jar!/:?]
	at com.sitewhere.server.SiteWhereTenantEngine.lifecycleStart(SiteWhereTenantEngine.java:206) [sitewhere-core-1.10.0.jar!/:?]
	at com.sitewhere.server.tenant.SiteWhereTenantEngineCommands$StartCommand.call(SiteWhereTenantEngineCommands.java:91) [sitewhere-core-1.10.0.jar!/:?]
	at com.sitewhere.server.tenant.SiteWhereTenantEngineCommands$StartCommand.call(SiteWhereTenantEngineCommands.java:76) [sitewhere-core-1.10.0.jar!/:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: org.quartz.SchedulerException: Scheduler with name 'oedata' already exists.
	at org.quartz.impl.SchedulerRepository.bind(SchedulerRepository.java:80) ~[quartz-2.2.3.jar!/:?]
	at org.quartz.impl.DirectSchedulerFactory.createScheduler(DirectSchedulerFactory.java:529) ~[quartz-2.2.3.jar!/:?]
	at org.quartz.impl.DirectSchedulerFactory.createScheduler(DirectSchedulerFactory.java:415) ~[quartz-2.2.3.jar!/:?]
	at org.quartz.impl.DirectSchedulerFactory.createScheduler(DirectSchedulerFactory.java:372) ~[quartz-2.2.3.jar!/:?]
	at org.quartz.impl.DirectSchedulerFactory.createScheduler(DirectSchedulerFactory.java:330) ~[quartz-2.2.3.jar!/:?]
	at org.quartz.impl.DirectSchedulerFactory.createScheduler(DirectSchedulerFactory.java:298) ~[quartz-2.2.3.jar!/:?]
	at com.sitewhere.server.scheduling.QuartzScheduleManager.setTenant(QuartzScheduleManager.java:79) ~[sitewhere-core-1.10.0.jar!/:?]
	... 12 more

**Comment by derekadams** [comment]
Can you provide some information about what you were doing when the error occurred? It looks like a tenant was being started, but we need to be able to reproduce the issue.

**Comment by bdyz1016** [comment]
I stopped the sitewhere process and launch the recompile the project.Go to the Tenant page and clicked switch button.
![image](https://cloud.githubusercontent.com/assets/10844401/26435334/23137714-4141-11e7-86d3-5bb0a17e76fa.png

**Comment by bdyz1016** [comment]
<img width="411" alt="44847381-7055-4fbb-ae2e-fd6694190a60" src="https://cloud.githubusercontent.com/assets/10844401/26435385/7194eb70-4141-11e7-8124-b64c1fe74262.png">

**Comment by derekadams** [comment]
We are no longer able to reproduce this bug in the SiteWhere 2.0 platform and it does not seem to affect 1.14.0 either, so we are going to close the bug.
