### ISSUE TITLE
hi,sitewhere+hbase,started and got error in hrere.

### ISSUE THREAD

**Issue by wslyy99** [sitewhere/sitewhere#511]
2017-06-29T17:01:00,649 [SiteWhere Server] INFO  [GenericApplicationContext] Refreshing org.springframework.context.support.GenericApplicationContext@3589f33e: startup date [Thu Jun 29 17:01:00 CST 2017]; root of context hierarchy
2017-06-29T17:01:00,713 [SiteWhere Server] INFO  [PropertySourcesPlaceholderConfigurer] Loading properties file from URL [file:/usr/local/java/sitewhere/sitewhere2/conf/sitewhere.properties]
2017-06-29T17:01:01,095 [SiteWhere Server] WARN  [NativeCodeLoader] Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2017-06-29T17:01:01,167 [SiteWhere Server] WARN  [GenericApplicationContext] Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hbase': Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: org/apache/log4j/Level
2017-06-29T17:01:01,168 [SiteWhere Server] ERROR [SiteWhereServer] SiteWhere Server CE 1.11.0 state transitioned to ERROR.
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hbase': Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: org/apache/log4j/Level
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1578) ~[spring-beans-4.3.2.RELEASE.jar!/:4.3.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545) ~[spring-beans-4.3.2.RELEASE.jar!/:4.3.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482) ~[spring-beans-4.3.2.RELEASE.jar!/:4.3.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.2.RELEASE.jar!/:4.3.2.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.2.RELEASE.jar!/:4.3.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.3.2.RELEASE.jar!/:4.3.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.2.RELEASE.jar!/:4.3.2.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:776) ~[spring-beans-4.3.2.RELEASE.jar!/:4.3.2.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:861) ~[spring-context-4.3.2.RELEASE.jar!/:4.3.2.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541) ~[spring-context-4.3.2.RELEASE.jar!/:4.3.2.RELEASE]
	at com.sitewhere.configuration.ConfigurationUtils.buildGlobalContext(ConfigurationUtils.java:57) ~[sitewhere-core-1.11.0.jar!/:?]
	at com.sitewhere.server.SiteWhereServer.initializeSpringContext(SiteWhereServer.java:855) ~[sitewhere-core-1.11.0.jar!/:?]
	at com.sitewhere.server.SiteWhereServer.initialize(SiteWhereServer.java:751) ~[sitewhere-core-1.11.0.jar!/:?]
	at com.sitewhere.server.lifecycle.LifecycleComponent.lifecycleInitialize(LifecycleComponent.java:116) [sitewhere-core-1.11.0.jar!/:?]
	at com.sitewhere.SiteWhere.start(SiteWhere.java:52) [sitewhere-core-1.11.0.jar!/:?]
	at com.sitewhere.SiteWhereApplication$1.call(SiteWhereApplication.java:78) [sitewhere-core-1.11.0.jar!/:?]
	at com.sitewhere.SiteWhereApplication$1.call(SiteWhereApplication.java:72) [sitewhere-core-1.11.0.jar!/:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]

hi,i got this error,i used sitewhere+hbase,i started sitewhere 11 war(sitewhere-server-1.11.0.tgz)

and i fixed sitewhere-server.xml 

<sw:datastore>
			
			

			
			 <sw:hbase-datastore quorum="sandbox.hortonworks.com" zookeeperZnodeParent="/hbase-unsecure"/>

			
			<sw:groovy-user-model-initializer
				scriptPath="initializer/userModel.groovy" enabled="${user.init.enabled}" />

			
			<sw:groovy-tenant-model-initializer
				scriptPath="initializer/tenantModel.groovy" enabled="${tenant.init.enabled}" />

</sw:datastore>

please , why ? i am chinease coder,thx

**Comment by derekadams** [comment]
It looks like a bug was introduced when we refactored logging. We will try to get the bug fixed in the 1.13 release since 1.12 is already full.

**Comment by wslyy99** [comment]
thank you for your reply,I'd like to know when the 1.13 edition will be available? I also want to use HBase, before I have finished the installation environment, no matter how the configuration (sitewhere-server.xml) are "Error creating bean with name'hbase'of init method: Invocation failed; nested exception is java.lang.NoClassDefFoundError:", seems to Never mind and configuration of the HBase environment and I did not find the source of the 'hbase' initialization position now,or please tell me where, thank you again.

**Comment by derekadams** [comment]
SiteWhere 1.12 will be released in mid-July and SiteWhere 1.13 will be released by mid-August.

**Comment by linzxs20041090** [comment]
I have the same problem on  Error creating bean with name 'hbase': Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: org/apache/log4j/Level.  
I need sitewhere directly use hbase fro datastore in IOT bigdata project.  I pasted my "sitewhere-server.xml" document here:
<sw:datastore>

			
			

			
			
                        <sw:hbase-datastore quorum="10.0.104.20,10.0.104.21,10.0.104.22" zookeeperClientPort="2181"/>
                         
			
			<sw:groovy-user-model-initializer
				scriptPath="initializer/userModel.groovy" enabled="${user.init.enabled}" />

			
			<sw:groovy-tenant-model-initializer
				scriptPath="initializer/tenantModel.groovy" enabled="${tenant.init.enabled}" />

		</sw:datastore>
