### ISSUE TITLE
Sitewhere Exception during try to Create Twilio Command Destination: The content of element 'sw:twilio-command-destination' is not complete

### ISSUE THREAD

**Issue by anhdenday** [sitewhere/sitewhere#55]
Hi @derekadams ,

I am trying to Create Twilio Command Destination. After I fill the exactly my information at "Destination id", "Account SID", "Authorization token", and "From phone number" then I click on "Stage Updates" then I receive below message 

> "Tenant has staged updates that have not been applied. Restart tenant to apply changes." 

therefore I restart tenant but the exception appear on the log below.

> Caused by: org.xml.sax.SAXParseException; lineNumber: 56; columnNumber: 187; cvc-complex-type.2.4.b: The content of element 'sw:twilio-command-destination' is not complete. One of '{"http://www.sitewhere.com/schema/sitewhere/ce/tenant":abstract-command-encoder}' is expected.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:134)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:396)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:284)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator$XSIErrorReporter.reportError(XMLSchemaValidator.java:452)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.reportSchemaError(XMLSchemaValidator.java:3230)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.elementLocallyValidComplexType(XMLSchemaValidator.java:3206)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.elementLocallyValidType(XMLSchemaValidator.java:3153)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.processElementContent(XMLSchemaValidator.java:3055)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.handleEndElement(XMLSchemaValidator.java:2134)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.emptyElement(XMLSchemaValidator.java:769)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:357)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2787)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:118)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:243)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
	at org.springframework.beans.factory.xml.DefaultDocumentLoader.loadDocument(DefaultDocumentLoader.java:76)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadDocument(XmlBeanDefinitionReader.java:429)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:391)
	... 11 more
And in the tenant page will see that tenant status is error.
![screen shot 2016-08-17 at 11 35 03 pm](https://cloud.githubusercontent.com/assets/6926208/17744813/85f2f1de-64d3-11e6-97e0-643d74d23d3a.png)

Please take a look. 
Thanks you

**Comment by derekadams** [comment]
After filling in the basic details for the command destination, you have to click the green arrow to fill out the required sub-elements. It looks like there is a bug in the tenant configuration editor for the Twilio destination though. It does not give any options for the encoder or parameter extractor.

![image](https://cloud.githubusercontent.com/assets/338921/17745407/a8eeb8ee-6479-11e6-95d9-721670e8fc40.png)

I added a Jira ticket to make sure it's fixed for the 1.9.0 release:

https://sitewhere.atlassian.net/browse/SITEWHERE-334

 In the meantime, you can add entries to the tenant XML configuration manually to get around the problem. You will need a String command encoder that will take your command payload and format it as a String for delivery via SMS. You will also need an SMS parameter extractor to pull the destination phone number from the device metadata.

Regards,
Derek

**Comment by anhdenday** [comment]
I try to config manually at sitewhere-tenant.xml after that restart the tenant but still same exception above.

> 
> 		<sw:twilio-command-destination destinationId="laipac"
> 			accountSid="AC08dad5a8e34899a81f76aa5d6d8981d7" authToken="9d24c11db0a961a51adc4c0f5397cea9" 
> 			fromPhoneNumber="0965350999">
> 			<sw:protobuf-command-encoder/>
> 			<sw:parameter-extractor ref="laipacExtractor"/>
> 		</sw:twilio-command-destination>

Hope It's will fix soon 

Thanks
