### ISSUE TITLE
XML parsing error when adding filters to outbound connectors

### ISSUE THREAD

**Issue by derekadams** [sitewhere/sitewhere#692]
There are no examples or documentation related to using Groovy filters on outbound processors. Since this is a common requirement, an example and documentation should be added as soon as possible.

**Comment by derekadams** [comment]
```
2019-02-12 07:15:10.468 ERROR 1 --- [nt Operations 2] c.s.c.m.OutboundConnectorsMicroservice   : Unable to bootstrap tenant engine.

java.util.concurrent.CompletionException: com.sitewhere.spi.ServerStartupException: Error initializing 'OutboundConnectorsTenantEngine'
 at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292) ~[na:1.8.0_191]
 at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308) ~[na:1.8.0_191]
 at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:943) ~[na:1.8.0_191]
 at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926) ~[na:1.8.0_191]
 at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[na:1.8.0_191]
 at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977) ~[na:1.8.0_191]
 at com.sitewhere.microservice.multitenant.operations.InitializeTenantEngineOperation.call(InitializeTenantEngineOperation.java:96) ~[sitewhere-microservice-2.0.4.jar!/:na]
 at com.sitewhere.microservice.multitenant.operations.InitializeTenantEngineOperation.call(InitializeTenantEngineOperation.java:35) ~[sitewhere-microservice-2.0.4.jar!/:na]
 at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_191]
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_191]
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_191]
 at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_191]
Caused by: com.sitewhere.spi.ServerStartupException: Error initializing 'OutboundConnectorsTenantEngine'
 at com.sitewhere.server.lifecycle.LifecycleComponent.initializeNestedComponent(LifecycleComponent.java:238) ~[sitewhere-core-lifecycle-2.0.4.jar!/:na]
 at com.sitewhere.microservice.multitenant.operations.InitializeTenantEngineOperation.call(InitializeTenantEngineOperation.java:79) ~[sitewhere-microservice-2.0.4.jar!/:na]
 ... 5 common frames omitted
Caused by: com.sitewhere.spi.SiteWhereException: Unable to load module configuration.
 at com.sitewhere.microservice.multitenant.MicroserviceTenantEngine.loadModuleConfiguration(MicroserviceTenantEngine.java:179) ~[sitewhere-microservice-2.0.4.jar!/:na]
 at com.sitewhere.microservice.multitenant.MicroserviceTenantEngine.initialize(MicroserviceTenantEngine.java:106) ~[sitewhere-microservice-2.0.4.jar!/:na]
 at com.sitewhere.server.lifecycle.LifecycleComponent.lifecycleInitialize(LifecycleComponent.java:183) ~[sitewhere-core-lifecycle-2.0.4.jar!/:na]
 at com.sitewhere.server.lifecycle.LifecycleComponent.initializeNestedComponent(LifecycleComponent.java:234) ~[sitewhere-core-lifecycle-2.0.4.jar!/:na]
 ... 6 common frames omitted
Caused by: org.springframework.beans.factory.xml.XmlBeanDefinitionStoreException: Line 350 in XML document from InputStream resource [resource loaded through InputStream] is invalid; nested exception is org.xml.sax.SAXParseException; systemId: https://sitewhere.io/schema/sitewhere/microservice/outbound-connectors/current/outbound-connectors.xsd; lineNumber: 350; columnNumber: 40; src-resolve: Cannot resolve the name 'cn:mqtt-broker-attributes' to a(n) 'attribute group' component.
 at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:398) ~[spring-beans-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
 at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:335) ~[spring-beans-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
 at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:303) ~[spring-beans-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
 at com.sitewhere.configuration.ConfigurationUtils.buildSubcontext(ConfigurationUtils.java:76) ~[sitewhere-core-2.0.4.jar!/:na]
 at com.sitewhere.microservice.multitenant.MicroserviceTenantEngine.loadModuleConfiguration(MicroserviceTenantEngine.java:175) ~[sitewhere-microservice-2.0.4.jar!/:na]
 ... 9 common frames omitted
ÕÅÎÄ½­ 2-12 15:21:59
Caused by: org.xml.sax.SAXParseException: src-resolve: Cannot resolve the name 'cn:mqtt-broker-attributes' to a(n) 'attribute group' component.
 at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203) ~[na:1.8.0_191]
 at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:134) ~[na:1.8.0_191]
 at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:396) ~[na:1.8.0_191]
 at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.reportSchemaErr(XSDHandler.java:4154) ~[na:1.8.0_191]
 at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.reportSchemaError(XSDHandler.java:4137) ~[na:1.8.0_191]
 at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.getGlobalDecl(XSDHandler.java:1684) ~[na:1.8.0_191]
 at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDAttributeGroupTraverser.traverseLocal(XSDAttributeGroupTraverser.java:80) ~[na:1.8.0_191]
 at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDAbstractTraverser.traverseAttrsAndAttrGrps(XSDAbstractTraverser.java:643) ~[na:1.8.0_191]
 at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDComplexTypeTraverser.processComplexContent(XSDComplexTypeTraverser.java:1123) ~[na:1.8.0_191]
 at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDComplexTypeTraverser.traverseComplexContent(XSDComplexTypeTraverser.java:836) ~[na:1.8.0_191]
 at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDComplexTypeTraverser.traverseComplexTypeDecl(XSDComplexTypeTraverser.java:315) ~[na:1.8.0_191]
 at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDComplexTypeTraverser.traverseGlobal(XSDComplexTypeTraverser.java:191) ~[na:1.8.0_191]
 at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.traverseGlobalDecl(XSDHandler.java:1894) ~[na:1.8.0_191]
 at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.getGlobalDecl(XSDHandler.java:1782) ~[na:1.8.0_191]
 at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDElementTraverser.traverseNamedElement(XSDElementTraverser.java:405) ~[na:1.8.0_191]
 at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDElementTraverser.traverseGlobal(XSDElementTraverser.java:242) ~[na:1.8.0_191]
 at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.traverseSchemas(XSDHandler.java:1439) ~[na:1.8.0_191]
 at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.parseSchema(XSDHandler.java:635) ~[na:1.8.0_191]
 at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadSchema(XMLSchemaLoader.java:610) ~[na:1.8.0_191]
 at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.findSchemaGrammar(XMLSchemaValidator.java:2447) ~[na:1.8.0_191]
 at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.handleStartElement(XMLSchemaValidator.java:1768) ~[na:1.8.0_191]
 at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.startElement(XMLSchemaValidator.java:741) ~[na:1.8.0_191]
 at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:374) ~[na:1.8.0_191]
 at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2784) ~[na:1.8.0_191]
 at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602) ~[na:1.8.0_191]

ÕÅÎÄ½­ 2-12 15:22:01
 at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112) ~[na:1.8.0_191]
 at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505) ~[na:1.8.0_191]
 at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842) ~[na:1.8.0_191]
 at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771) ~[na:1.8.0_191]
 at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141) ~[na:1.8.0_191]
 at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:243) ~[na:1.8.0_191]
 at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339) ~[na:1.8.0_191]
 at org.springframework.beans.factory.xml.DefaultDocumentLoader.loadDocument(DefaultDocumentLoader.java:77) ~[spring-beans-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
 at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadDocument(XmlBeanDefinitionReader.java:428) ~[spring-beans-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
 at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:390) ~[spring-beans-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
 ... 13 common frames omitted
```
