### ISSUE TITLE
Device registration microservice API channel / Consul errors

### ISSUE THREAD

**Issue by derekadams** [sitewhere/sitewhere#697]
In cases such as backup/restore where services are scaled to 0 and back up, the device registration microservice reports error getting an API channel to other services and also is not able to register with Consul.

**Comment by derekadams** [comment]
![image](https://user-images.githubusercontent.com/338921/53649421-17ec0d80-3c10-11e9-99a9-a00dd5d2f74b.png)

**Comment by derekadams** [comment]
```
com.sitewhere.spi.SiteWhereException: Unable to send heartbeat.
 at com.sitewhere.microservice.discovery.consul.ConsulServiceDiscoveryProvider.sendHeartbeat(ConsulServiceDiscoveryProvider.java:154) ~[sitewhere-microservice-2.0.5.jar!/:na]
 at com.sitewhere.microservice.Microservice$Heartbeat.run(Microservice.java:736) ~[sitewhere-microservice-2.0.5.jar!/:na]
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_191]
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_191]
 at java.lang.Thread.run(Thread.java:748) [na:1.8.0_191]
Caused by: com.orbitz.consul.NotRegisteredException: Error checking state
 at com.orbitz.consul.AgentClient.check(AgentClient.java:473) ~[consul-client-1.2.3.jar!/:na]
 at com.orbitz.consul.AgentClient.checkTtl(AgentClient.java:484) ~[consul-client-1.2.3.jar!/:na]
 at com.orbitz.consul.AgentClient.pass(AgentClient.java:491) ~[consul-client-1.2.3.jar!/:na]
 at com.sitewhere.microservice.discovery.consul.ConsulServiceDiscoveryProvider.sendHeartbeat(ConsulServiceDiscoveryProvider.java:151) ~[sitewhere-microservice-2.0.5.jar!/:na]
 ... 4 common frames omitted
Caused by: com.orbitz.consul.ConsulException: Consul request failed with status [500]: CheckID "service:4a174b3e-faf6-4692-95c3-36d3b8fe8bcd" does not have associated TTL
 at com.orbitz.consul.util.Http.ensureResponseSuccessful(Http.java:59) ~[consul-client-1.2.3.jar!/:na]
 at com.orbitz.consul.util.Http.handle(Http.java:37) ~[consul-client-1.2.3.jar!/:na]
 at com.orbitz.consul.AgentClient.check(AgentClient.java:471) ~[consul-client-1.2.3.jar!/:na]
 ... 7 common frames omitted
```
