### ISSUE TITLE
Some exceptions about consul microservice

### ISSUE THREAD

**Issue by GanKanTechnology** [sitewhere/sitewhere#702]
Hi guys ~

I've deployed sitewhere with k8s and everything went well at first. But then several hours later or days later something begun to go wrong, such as we cannot login the admin-ui, or we cannot see all data from the admin-ui. Then I checked the  logs from almost all microservices and divided the exceptions into two categories :

```
Category 1.  Caused by: com.orbitz.consul.NotRegisteredException: Error checking state
 at com.orbitz.consul.AgentClient.check(AgentClient.java:473) ~[consul-client-1.2.3.jar!/:na]
......
Caused by: com.orbitz.consul.ConsulException: Consul request failed with status [500]: CheckID "service:a1b895c6-3e53-492c-9362-c2602474ebb1" does not have associated TTL
......
```

```
Category 2. [ice Heartbeat 1] c.s.e.m.EventManagementMicroservice      : Unable to send state for heartbeat.
com.orbitz.consul.ConsulException: Consul request failed
 at com.orbitz.consul.util.Http.executeCall(Http.java:51) ~[consul-client-1.2.3.jar!/:na]
......
Caused by: java.net.SocketTimeoutException: timeout
......
Caused by: java.net.SocketException: Socket closed
```

The first category like "CheckID "service:a1b895c6-3e53-492c-9362-c2602474ebb1" does not have associated TTL" , I guess that's the major cause  which can lead to other exceptions. The second category may be subordinate.

I don't konw how to solve this yet so I submit this issue. Hope you can find out why and fix it in the sitewhere-2.0.6 or later. If there's any other information that need to supplement, please let me know.

Thanks a lot.

p.s. here is one of the exception logs from the outbound-connectors microservice , just for reference.

```
2019-04-02 18:56:54.074 ERROR 1 --- [ice Heartbeat 1] c.s.c.m.OutboundConnectorsMicroservice   : Unable to send state for heartbeat.

com.sitewhere.spi.SiteWhereException: Unable to send heartbeat.
	at com.sitewhere.microservice.discovery.consul.ConsulServiceDiscoveryProvider.sendHeartbeat(ConsulServiceDiscoveryProvider.java:154) ~[sitewhere-microservice-2.0.5.jar!/:na]
	at com.sitewhere.microservice.Microservice$Heartbeat.run(Microservice.java:736) ~[sitewhere-microservice-2.0.5.jar!/:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_191]
Caused by: com.orbitz.consul.NotRegisteredException: Error checking state
	at com.orbitz.consul.AgentClient.check(AgentClient.java:473) ~[consul-client-1.2.3.jar!/:na]
	at com.orbitz.consul.AgentClient.checkTtl(AgentClient.java:484) ~[consul-client-1.2.3.jar!/:na]
	at com.orbitz.consul.AgentClient.pass(AgentClient.java:491) ~[consul-client-1.2.3.jar!/:na]
	at com.sitewhere.microservice.discovery.consul.ConsulServiceDiscoveryProvider.sendHeartbeat(ConsulServiceDiscoveryProvider.java:151) ~[sitewhere-microservice-2.0.5.jar!/:na]
	... 4 common frames omitted
Caused by: com.orbitz.consul.ConsulException: Consul request failed with status [500]: CheckID "service:51cdaeeb-4283-4e58-9c7f-32ee90973741" does not have associated TTL
	at com.orbitz.consul.util.Http.ensureResponseSuccessful(Http.java:59) ~[consul-client-1.2.3.jar!/:na]
	at com.orbitz.consul.util.Http.handle(Http.java:37) ~[consul-client-1.2.3.jar!/:na]
	at com.orbitz.consul.AgentClient.check(AgentClient.java:471) ~[consul-client-1.2.3.jar!/:na]
	... 7 common frames omitted
```

**Comment by derekadams** [comment]
Hi @GanKanTechnology I think this is the same bug reported in #697. We have added some new service discovery code in `2.0.6` that should help with these errors and prevent connections between microservices from dropping.
