### ISSUE TITLE
ClassNotFoundException: io.netty.channel.epoll.Epoll

### ISSUE THREAD

**Issue by CCThinkBank** [sitewhere/sitewhere#792]
ALL the subproject has bellow error. 

java.lang.ClassNotFoundException: io.netty.channel.epoll.Epoll
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_71]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_71]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[na:1.8.0_71]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_71]
	at java.lang.Class.forName0(Native Method) ~[na:1.8.0_71]
	at java.lang.Class.forName(Class.java:264) ~[na:1.8.0_71]
	at io.grpc.netty.Utils.getEpollUnavailabilityCause(Utils.java:235) [grpc-netty-1.21.0.jar:1.21.0]
	at io.grpc.netty.Utils.<clinit>(Utils.java:101) [grpc-netty-1.21.0.jar:1.21.0]
	at io.grpc.netty.NettyServerBuilder.<clinit>(NettyServerBuilder.java:78) [grpc-netty-1.21.0.jar:1.21.0]
	at com.sitewhere.microservice.grpc.GrpcServer.buildServer(GrpcServer.java:62) [main/:na]
	at com.sitewhere.microservice.grpc.GrpcServer.initialize(GrpcServer.java:88) [main/:na]
	at com.sitewhere.server.lifecycle.LifecycleComponent.lifecycleInitialize(LifecycleComponent.java:178) [main/:na]
	at com.sitewhere.server.lifecycle.LifecycleComponent.initializeNestedComponent(LifecycleComponent.java:225) [main/:na]
	at com.sitewhere.server.lifecycle.InitializeComponentLifecycleStep.execute(InitializeComponentLifecycleStep.java:48) [main/:na]
	at com.sitewhere.server.lifecycle.CompositeLifecycleStep.execute(CompositeLifecycleStep.java:77) [main/:na]
	at com.sitewhere.microservice.Microservice.initialize(Microservice.java:248) [main/:na]
	at com.sitewhere.microservice.configuration.ConfigurableMicroservice.initialize(ConfigurableMicroservice.java:249) [main/:na]
	at com.sitewhere.microservice.multitenant.MultitenantMicroservice.initialize(MultitenantMicroservice.java:41) [main/:na]
	at com.sitewhere.server.lifecycle.LifecycleComponent.lifecycleInitialize(LifecycleComponent.java:178) [main/:na]
	at com.sitewhere.microservice.MicroserviceApplication$StartMicroservice.startMicroservice(MicroserviceApplication.java:140) [main/:na]
	at com.sitewhere.microservice.MicroserviceApplication$StartMicroservice.call(MicroserviceApplication.java:97) [main/:na]
	at com.sitewhere.microservice.MicroserviceApplication$StartMicroservice.call(MicroserviceApplication.java:1) [main/:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_71]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_71]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_71]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_71]

**Comment by derekadams** [comment]
This is an exception recorded at the `DEBUG` level in Netty and is not within the control of SiteWhere. It's part of Netty auto-detecting which features are available at runtime. If you turn off debugging, the exception should not be shown.
