### ISSUE TITLE
Redis exception on microservice startup

### ISSUE THREAD

**Issue by derekadams** [sitewhere/sitewhere#831]
When restarting microservices on top of a running infrastructure, the microservices sometimes fail with the following exception:

```
2020-06-22 13:33:24,284 ERROR [com.sit.dev.mic.DeviceManagementMicroservice] (Service Main) Exception on microservice startup.: com.sitewhere.spi.SiteWhereException: org.redisson.client.RedisException: ERR Error running script (call to f_8919eb76e65d79f3402d25a746d81a6ef0a57704): @user_script:1: @user_script: 1: -READONLY You can't write against a read only replica.   . channel: [id: 0xbd35639c, L:/172.17.0.37:32804 - R:10.110.57.108/10.110.57.108:6379] command: (EVAL), params: [local v = redis.call('hget', KEYS[1], ARGV[1]); redis.call('hset', KEYS[1], ARGV[1], ARGV[2]); retur..., 1, bubba, PooledUnsafeDirectByteBuf(ridx: 0, widx: 10, cap: 256), PooledUnsafeDirectByteBuf(ridx: 0, widx: 6, cap: 256)]
at com.sitewhere.microservice.lifecycle.LifecycleComponent.lifecycleInitialize(LifecycleComponent.java:206)
at com.sitewhere.device.microservice.DeviceManagementMicroservice_ClientProxy.lifecycleInitialize(DeviceManagementMicroservice_ClientProxy.zig:1536)
at com.sitewhere.microservice.MicroserviceApplication.startMicroservice(MicroserviceApplication.java:118)
at com.sitewhere.microservice.MicroserviceApplication$StartMicroservice.call(MicroserviceApplication.java:155)
at com.sitewhere.microservice.MicroserviceApplication$StartMicroservice.call(MicroserviceApplication.java:147)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: org.redisson.client.RedisException: ERR Error running script (call to f_8919eb76e65d79f3402d25a746d81a6ef0a57704): @user_script:1: @user_script: 1: -READONLY You can't write against a read only replica.   . channel: [id: 0xbd35639c, L:/172.17.0.37:32804 - R:10.110.57.108/10.110.57.108:6379] command: (EVAL), params: [local v = redis.call('hget', KEYS[1], ARGV[1]); redis.call('hset', KEYS[1], ARGV[1], ARGV[2]); retur..., 1, bubba, PooledUnsafeDirectByteBuf(ridx: 0, widx: 10, cap: 256), PooledUnsafeDirectByteBuf(ridx: 0, widx: 6, cap: 256)]
at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:355)
at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:196)
at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:134)
at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:104)
at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:493)
at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:271)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
```

**Comment by derekadams** [comment]
There was leftover testing logic in the common Redis initialization code which fired a write/read immediately after the client was created. This code was removed so that it didn't affect microservice initialization. This seems to have fixed the issue but we will need to see if it pops up somewhere else (e.g the first write operation after initialization).
