### ISSUE TITLE
Exception during forwards to Azure EventHub

### ISSUE THREAD

**Issue by Abel-Liu** [sitewhere/sitewhere#84]
Hi, I got some errors after using Azure EventHub Processor. Can you help me?

I am running SiteWhere 1.8.0 on Windows, and send data to SiteWhere every 5 seconds from Raspberry Pi (using MQTT).

1
```
java.util.ConcurrentModificationException
at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
at java.util.ArrayList$Itr.next(Unknown Source)
at org.apache.qpid.amqp_1_0.messaging.SectionEncoderImpl.getEncoding(SectionEncoderImpl.java:60)
at org.apache.qpid.amqp_1_0.client.Sender.send(Sender.java:277)
at org.apache.qpid.amqp_1_0.jms.impl.MessageProducerImpl.send(MessageProducerImpl.java:321)
at org.apache.qpid.amqp_1_0.jms.impl.MessageProducerImpl.send(MessageProducerImpl.java:240)
at com.sitewhere.azure.device.communication.EventHubOutboundEventProcessor.sendEvent(EventHubOutboundEventProcessor.java:211)
at com.sitewhere.azure.device.communication.EventHubOutboundEventProcessor.onMeasurementsNotFiltered(EventHubOutboundEventProcessor.java:151)
at com.sitewhere.device.event.processor.FilteredOutboundEventProcessor.onMeasurements(FilteredOutboundEventProcessor.java:84)
at com.sitewhere.device.event.processor.DefaultOutboundEventProcessorChain.onMeasurements(DefaultOutboundEventProcessorChain.java:137)
at com.sitewhere.device.communication.BlockingQueueOutboundProcessingStrategy$BlockingDeviceEventProcessor.run(BlockingQueueOutboundProcessingStrategy.java:243)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
```

2
```
ERROR [BlockingQueueOutboundProcessingStrategy] Unhandled exception in outbound event processing.
java.lang.ArrayIndexOutOfBoundsException
at java.lang.System.arraycopy(Native Method)
at org.apache.qpid.amqp_1_0.messaging.SectionEncoderImpl.getEncoding(SectionEncoderImpl.java:63)
at org.apache.qpid.amqp_1_0.client.Sender.send(Sender.java:277)
at org.apache.qpid.amqp_1_0.jms.impl.MessageProducerImpl.send(MessageProducerImpl.java:321)
at org.apache.qpid.amqp_1_0.jms.impl.MessageProducerImpl.send(MessageProducerImpl.java:240)
at com.sitewhere.azure.device.communication.EventHubOutboundEventProcessor.sendEvent(EventHubOutboundEventProcessor.java:211)
at com.sitewhere.azure.device.communication.EventHubOutboundEventProcessor.onLocationNotFiltered(EventHubOutboundEventProcessor.java:162)
at com.sitewhere.device.event.processor.FilteredOutboundEventProcessor.onLocation(FilteredOutboundEventProcessor.java:107)
at com.sitewhere.device.event.processor.DefaultOutboundEventProcessorChain.onLocation(DefaultOutboundEventProcessorChain.java:161)
at com.sitewhere.device.communication.BlockingQueueOutboundProcessingStrategy$BlockingDeviceEventProcessor.run(BlockingQueueOutboundProcessingStrategy.java:247)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
```

These two errors happened every time after I start sending data several minutes.

3

```
ERROR [DefaultOutboundEventProcessorChain] com.sitewhere.spi.SiteWhereException: javax.jms.IllegalStateException: Closed
```

This error happened when I stop sending data and restart several minutes later.

**Comment by derekadams** [comment]
It looks like a bug in the Apache Qpid code. The version included in SiteWhere is one that was provided by the Microsoft team. It includes some customization, so we need to do some testing to see if it is possible to upgrade to the latest version without causing problems. We added a Jira ticket for tracking:

https://sitewhere.atlassian.net/browse/SITEWHERE-367

**Comment by Abel-Liu** [comment]
Thanks very much for your working.

**Comment by derekadams** [comment]
The Azure EventHub support has been rewritten for 2.0 and now uses the Microsoft libraries rather than 3rd party clients.
