### ISSUE TITLE
SiteWhere 1.9.0 GroovyRouteBuilder NullPointerException

### ISSUE THREAD

**Issue by Murdochcb** [sitewhere/sitewhere#86]
SiteWhere version 1.9.0 fails to execute an MqttOutboundEventProcessor with attached GroovyRouteBuilder, throwing a NullPointerException. It appears that the GroovyConfiguration is not actually injected into the class, and thus cannot execute scripts. This was previously working in SiteWhere version 1.8.0.

The code in GroovyRouteBuilder executes scripts in the following way:
Object result = getConfiguration().getGroovyScriptEngine().run(getScriptPath(), binding);

The GroovyEventProcessor class functions correctly, and executes scripts in this way:
SiteWhere.getServer().getTenantGroovyConfiguration(getTenant()).getGroovyScriptEngine().run(getScriptPath(), binding);

Should the GroovyRouteBuilder not be using the TenantGroovyConfiguration instead? This seems more aligned with rest of outbound processing chain.

Stack Trace of error is below:
[SiteWhere BlockingQueueOutboundProcessingStrategy Processor 2] ERROR [BlockingQueueOutboundProcessingStrategy] Unhandled exception in outbound event processing.
java.lang.NullPointerException
        at com.sitewhere.groovy.device.event.processor.routing.GroovyRouteBuilder.build(GroovyRouteBuilder.java:57) ~[sitewhere-core-1.9.0.jar!/:?]
        at com.sitewhere.groovy.device.event.processor.routing.GroovyRouteBuilder.build(GroovyRouteBuilder.java:29) ~[sitewhere-core-1.9.0.jar!/:?]
        at com.sitewhere.device.communication.mqtt.MqttOutboundEventProcessor.sendEvent(MqttOutboundEventProcessor.java:223) ~[sitewhere-core-1.9.0.jar!/:?]
        at com.sitewhere.device.communication.mqtt.MqttOutboundEventProcessor.onCommandInvocationNotFiltered(MqttOutboundEventProcessor.java:191) ~[sitewhere-core-1.9.0.jar!/:?]
        at com.sitewhere.device.event.processor.FilteredOutboundEventProcessor.onCommandInvocation(FilteredOutboundEventProcessor.java:189) ~[sitewhere-core-1.9.0.jar!/:?]
        at com.sitewhere.device.event.processor.DefaultOutboundEventProcessorChain.onCommandInvocation(DefaultOutboundEventProcessorChain.java:196) ~[sitewhere-core-1.9.0.jar!/:?]
        at com.sitewhere.device.communication.BlockingQueueOutboundProcessingStrategy$BlockingDeviceEventProcessor.run(BlockingQueueOutboundProcessingStrategy.java:260) [sitewhere-core-1.9.0.jar!/:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_65]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_65]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_65]

**Comment by derekadams** [comment]
Thanks for reporting the issue. We added a Jira ticket to make sure it is addressed in the 1.10.0 release:

https://sitewhere.atlassian.net/browse/SITEWHERE-368

As you mentioned, this is due to the updates for Groovy processing for 1.9.0. Previously, the Groovy configuration was injected by Spring, but now it should be referenced directly since it is part of the core server API. We are looking at adding test cases to make sure these regressions do not happen in the future.
