### ISSUE TITLE
Cannot start Socket Event Source v1.9

### ISSUE THREAD

**Issue by supnobita** [sitewhere/sitewhere#93]
Dear Dereck, Sitewhere team,
I use Socket Event Source to receive data from my device. My sitewhere version is: 1.9. I have configured the socket event source like this picture:  https://lh3.googleusercontent.com/-MbBogDXmXco/V7SNrGokWVI/AAAAAAAAALo/Rn1YHUvr9Xsb1knsyJjcjt7jSgdfqesGwCLcB/s1600/socket-event-processor.png
I put my groovy code at: /opt/sitewhere/conf/global/scripts/groovy/ and event at /opt/sitewhere/conf/tenants/default/scripts/groovy/ .
But when i restart my tenant (ex: default), it cannt start, SW give me error:

> 
d 10 threads.
2017-03-06T16:11:15,972 [pool-9-thread-1] INFO  [BlockingQueueInboundProcessingStrategy] BlockingQueueInboundProcessingStrategy state transitioned to STARTED.
2017-03-06T16:11:15,973 [pool-9-thread-1] INFO  [EventProcessing] EventProcessing state transitioned to STARTED.
2017-03-06T16:11:15,973 [pool-9-thread-1] INFO  [DefaultDeviceCommunication] DefaultDeviceCommunication state transitioned to STARTING.
2017-03-06T16:11:15,973 [pool-9-thread-1] INFO  [DefaultCommandProcessingStrategy] DefaultCommandProcessingStrategy state transitioned to STARTING.
2017-03-06T16:11:15,973 [pool-9-thread-1] INFO  [DefaultCommandExecutionBuilder] DefaultCommandExecutionBuilder state transitioned to STARTING.
2017-03-06T16:11:15,973 [pool-9-thread-1] INFO  [DefaultCommandExecutionBuilder] DefaultCommandExecutionBuilder state transitioned to STARTED.
2017-03-06T16:11:15,973 [pool-9-thread-1] INFO  [DefaultCommandTargetResolver] DefaultCommandTargetResolver state transitioned to STARTING.
2017-03-06T16:11:15,973 [pool-9-thread-1] INFO  [DefaultCommandTargetResolver] DefaultCommandTargetResolver state transitioned to STARTED.
2017-03-06T16:11:15,973 [pool-9-thread-1] INFO  [DefaultCommandProcessingStrategy] DefaultCommandProcessingStrategy state transitioned to STARTED.
2017-03-06T16:11:15,973 [pool-9-thread-1] INFO  [CommandDestination] Command Destination (default) state transitioned to STARTING.
2017-03-06T16:11:15,973 [pool-9-thread-1] INFO  [ProtobufExecutionEncoder] ProtobufExecutionEncoder state transitioned to STARTING.
2017-03-06T16:11:15,973 [pool-9-thread-1] INFO  [ProtobufExecutionEncoder] ProtobufExecutionEncoder state transitioned to STARTED.
2017-03-06T16:11:15,973 [pool-9-thread-1] INFO  [HardwareIdMqttParameterExtractor] HardwareIdMqttParameterExtractor state transitioned to STARTING.
2017-03-06T16:11:15,973 [pool-9-thread-1] INFO  [HardwareIdMqttParameterExtractor] HardwareIdMqttParameterExtractor state transitioned to STARTED.
2017-03-06T16:11:15,973 [pool-9-thread-1] INFO  [MqttCommandDeliveryProvider] MqttCommandDeliveryProvider state transitioned to STARTING.
2017-03-06T16:11:15,973 [pool-9-thread-1] INFO  [MqttCommandDeliveryProvider] Connecting to MQTT broker at 'localhost:1883'...
2017-03-06T16:11:15,996 [pool-9-thread-1] INFO  [MqttCommandDeliveryProvider] Connected to MQTT broker.
2017-03-06T16:11:15,996 [pool-9-thread-1] INFO  [MqttCommandDeliveryProvider] MqttCommandDeliveryProvider state transitioned to STARTED.
2017-03-06T16:11:15,997 [pool-9-thread-1] INFO  [CommandDestination] Command Destination (default) state transitioned to STARTED.
2017-03-06T16:11:15,997 [pool-9-thread-1] INFO  [CommandDestination] Command Destination (hybrid) state transitioned to STARTING.
2017-03-06T16:11:15,997 [pool-9-thread-1] INFO  [ProtobufExecutionEncoder] JavaHybridProtobufExecutionEncoder state transitioned to STARTING.
2017-03-06T16:11:15,997 [pool-9-thread-1] INFO  [ProtobufExecutionEncoder] JavaHybridProtobufExecutionEncoder state transitioned to STARTED.
2017-03-06T16:11:15,997 [pool-9-thread-1] INFO  [HardwareIdMqttParameterExtractor] HardwareIdMqttParameterExtractor state transitioned to STARTING.
2017-03-06T16:11:15,997 [pool-9-thread-1] INFO  [HardwareIdMqttParameterExtractor] HardwareIdMqttParameterExtractor state transitioned to STARTED.
2017-03-06T16:11:15,997 [pool-9-thread-1] INFO  [MqttCommandDeliveryProvider] MqttCommandDeliveryProvider state transitioned to STARTING.
2017-03-06T16:11:15,997 [pool-9-thread-1] INFO  [MqttCommandDeliveryProvider] Connecting to MQTT broker at 'localhost:1883'...
2017-03-06T16:11:16,011 [pool-9-thread-1] INFO  [MqttCommandDeliveryProvider] Connected to MQTT broker.
2017-03-06T16:11:16,011 [pool-9-thread-1] INFO  [MqttCommandDeliveryProvider] MqttCommandDeliveryProvider state transitioned to STARTED.
2017-03-06T16:11:16,011 [pool-9-thread-1] INFO  [CommandDestination] Command Destination (hybrid) state transitioned to STARTED.
2017-03-06T16:11:16,011 [pool-9-thread-1] INFO  [CommandDestination] Command Destination (json) state transitioned to STARTING.
2017-03-06T16:11:16,012 [pool-9-thread-1] INFO  [JsonCommandExecutionEncoder] JsonCommandExecutionEncoder state transitioned to STARTING.
2017-03-06T16:11:16,012 [pool-9-thread-1] INFO  [JsonCommandExecutionEncoder] JsonCommandExecutionEncoder state transitioned to STARTED.
2017-03-06T16:11:16,012 [pool-9-thread-1] INFO  [HardwareIdMqttParameterExtractor] HardwareIdMqttParameterExtractor state transitioned to STARTING.
2017-03-06T16:11:16,012 [pool-9-thread-1] INFO  [HardwareIdMqttParameterExtractor] HardwareIdMqttParameterExtractor state transitioned to STARTED.
2017-03-06T16:11:16,012 [pool-9-thread-1] INFO  [MqttCommandDeliveryProvider] MqttCommandDeliveryProvider state transitioned to STARTING.
2017-03-06T16:11:16,012 [pool-9-thread-1] INFO  [MqttCommandDeliveryProvider] Connecting to MQTT broker at 'localhost:1883'...
2017-03-06T16:11:16,028 [pool-9-thread-1] INFO  [MqttCommandDeliveryProvider] Connected to MQTT broker.
2017-03-06T16:11:16,028 [pool-9-thread-1] INFO  [MqttCommandDeliveryProvider] MqttCommandDeliveryProvider state transitioned to STARTED.
2017-03-06T16:11:16,028 [pool-9-thread-1] INFO  [CommandDestination] Command Destination (json) state transitioned to STARTED.
2017-03-06T16:11:16,028 [pool-9-thread-1] INFO  [SpecificationMappingCommandRouter] SpecificationMappingCommandRouter state transitioned to STARTING.
2017-03-06T16:11:16,028 [pool-9-thread-1] INFO  [SpecificationMappingCommandRouter] SpecificationMappingCommandRouter state transitioned to STARTED.
2017-03-06T16:11:16,029 [pool-9-thread-1] INFO  [RegistrationManager] RegistrationManager state transitioned to STARTING.
2017-03-06T16:11:16,029 [pool-9-thread-1] INFO  [RegistrationManager] RegistrationManager state transitioned to STARTED.
2017-03-06T16:11:16,029 [pool-9-thread-1] INFO  [SymbolGeneratorManager] SymbolGeneratorManager state transitioned to STARTING.
2017-03-06T16:11:16,029 [pool-9-thread-1] INFO  [QrCodeSymbolGenerator] QrCodeSymbolGenerator state transitioned to STARTING.
2017-03-06T16:11:16,029 [pool-9-thread-1] INFO  [QrCodeSymbolGenerator] QrCodeSymbolGenerator state transitioned to STARTED.
2017-03-06T16:11:16,030 [pool-9-thread-1] INFO  [SymbolGeneratorManager] SymbolGeneratorManager state transitioned to STARTED.
2017-03-06T16:11:16,030 [pool-9-thread-1] INFO  [BatchOperationManager] BatchOperationManager state transitioned to STARTING.
2017-03-06T16:11:16,030 [pool-9-thread-1] INFO  [BatchOperationManager] BatchOperationManager state transitioned to STARTED.
2017-03-06T16:11:16,030 [pool-9-thread-1] INFO  [DeviceStreamManager] DeviceStreamManager state transitioned to STARTING.
2017-03-06T16:11:16,030 [pool-9-thread-1] INFO  [DeviceStreamManager] DeviceStreamManager state transitioned to STARTED.
2017-03-06T16:11:16,030 [pool-9-thread-1] INFO  [DevicePresenceManager] DevicePresenceManager state transitioned to STARTING.
2017-03-06T16:11:16,030 [pool-9-thread-1] INFO  [DevicePresenceManager] DevicePresenceManager state transitioned to STARTED.
2017-03-06T16:11:16,030 [pool-9-thread-1] INFO  [InboundEventSource] Event Source (protobuf) state transitioned to STARTING.
2017-03-06T16:11:16,030 [pool-9-thread-1] INFO  [ProtobufDeviceEventDecoder] ProtobufDeviceEventDecoder state transitioned to STARTING.
2017-03-06T16:11:16,030 [pool-9-thread-1] INFO  [ProtobufDeviceEventDecoder] ProtobufDeviceEventDecoder state transitioned to STARTED.
2017-03-06T16:11:16,030 [pool-9-thread-1] INFO  [MqttInboundEventReceiver] MqttInboundEventReceiver state transitioned to STARTING.
2017-03-06T16:11:16,030 [pool-9-thread-1] INFO  [MqttInboundEventReceiver] Receiver connecting to MQTT broker at 'tcp://localhost:1883'...
2017-03-06T16:11:16,031 [pool-47-thread-1] INFO  [DevicePresenceManager] Presence manager checking every 5m (300 seconds) for devices with last interaction date of more than 8h (28800 seconds) .
2017-03-06T16:11:16,047 [pool-9-thread-1] INFO  [MqttInboundEventReceiver] Receiver connected to MQTT broker.
2017-03-06T16:11:16,049 [pool-9-thread-1] INFO  [MqttInboundEventReceiver] Subscribed to events on MQTT topic: SiteWhere/input/protobuf
2017-03-06T16:11:16,050 [pool-9-thread-1] INFO  [MqttInboundEventReceiver] MqttInboundEventReceiver state transitioned to STARTED.
2017-03-06T16:11:16,050 [pool-9-thread-1] INFO  [InboundEventSource] Event Source (protobuf) state transitioned to STARTED.
2017-03-06T16:11:16,050 [pool-9-thread-1] INFO  [InboundEventSource] Event Source (json) state transitioned to STARTING.
2017-03-06T16:11:16,050 [pool-9-thread-1] INFO  [JsonDeviceRequestDecoder] JsonDeviceRequestDecoder state transitioned to STARTING.
2017-03-06T16:11:16,050 [pool-9-thread-1] INFO  [JsonDeviceRequestDecoder] JsonDeviceRequestDecoder state transitioned to STARTED.
2017-03-06T16:11:16,050 [pool-9-thread-1] INFO  [MqttInboundEventReceiver] MqttInboundEventReceiver state transitioned to STARTING.
2017-03-06T16:11:16,050 [pool-9-thread-1] INFO  [MqttInboundEventReceiver] Receiver connecting to MQTT broker at 'tcp://localhost:1883'...
2017-03-06T16:11:16,052 [SiteWhere MQTT(protobuf - SiteWhere/input/protobuf) Receiver 1] INFO  [MqttInboundEventReceiver] Started MQTT subscription processing thread.
2017-03-06T16:11:16,064 [pool-9-thread-1] INFO  [MqttInboundEventReceiver] Receiver connected to MQTT broker.
2017-03-06T16:11:16,066 [pool-9-thread-1] INFO  [MqttInboundEventReceiver] Subscribed to events on MQTT topic: SiteWhere/input/json
2017-03-06T16:11:16,066 [pool-9-thread-1] INFO  [MqttInboundEventReceiver] MqttInboundEventReceiver state transitioned to STARTED.
2017-03-06T16:11:16,066 [pool-9-thread-1] INFO  [InboundEventSource] Event Source (json) state transitioned to STARTED.
2017-03-06T16:11:16,066 [pool-9-thread-1] INFO  [InboundEventSource] Event Source (json-batch) state transitioned to STARTING.
2017-03-06T16:11:16,067 [pool-9-thread-1] INFO  [JsonBatchEventDecoder] JsonBatchEventDecoder state transitioned to STARTING.
2017-03-06T16:11:16,067 [pool-9-thread-1] INFO  [JsonBatchEventDecoder] JsonBatchEventDecoder state transitioned to STARTED.
2017-03-06T16:11:16,067 [pool-9-thread-1] INFO  [MqttInboundEventReceiver] MqttInboundEventReceiver state transitioned to STARTING.
2017-03-06T16:11:16,067 [pool-9-thread-1] INFO  [MqttInboundEventReceiver] Receiver connecting to MQTT broker at 'tcp://localhost:1883'...
2017-03-06T16:11:16,067 [SiteWhere MQTT(json - SiteWhere/input/json) Receiver 1] INFO  [MqttInboundEventReceiver] Started MQTT subscription processing thread.
2017-03-06T16:11:16,070 [pool-9-thread-1] INFO  [MqttInboundEventReceiver] Receiver connected to MQTT broker.
2017-03-06T16:11:16,072 [pool-9-thread-1] INFO  [MqttInboundEventReceiver] Subscribed to events on MQTT topic: SiteWhere/input/jsonbatch
2017-03-06T16:11:16,072 [pool-9-thread-1] INFO  [MqttInboundEventReceiver] MqttInboundEventReceiver state transitioned to STARTED.
2017-03-06T16:11:16,072 [pool-9-thread-1] INFO  [InboundEventSource] Event Source (json-batch) state transitioned to STARTED.
2017-03-06T16:11:16,072 [pool-9-thread-1] INFO  [InboundEventSource] Event Source (inputdata) state transitioned to STARTING.
2017-03-06T16:11:16,072 [pool-9-thread-1] INFO  [JsonDeviceRequestDecoder] JsonDeviceRequestDecoder state transitioned to STARTING.
2017-03-06T16:11:16,072 [pool-9-thread-1] INFO  [JsonDeviceRequestDecoder] JsonDeviceRequestDecoder state transitioned to STARTED.
2017-03-06T16:11:16,072 [pool-9-thread-1] INFO  [SocketInboundEventReceiver] BinarySocketInboundEventReceiver state transitioned to STARTING.
2017-03-06T16:11:16,072 [pool-9-thread-1] ERROR [SocketInboundEventReceiver] BinarySocketInboundEventReceiver state transitioned to ERROR.
java.lang.NullPointerException
2017-03-06T16:11:16,072 [SiteWhere MQTT(json-batch - SiteWhere/input/jsonbatch) Receiver 1] INFO  [MqttInboundEventReceiver] Started MQTT subscription processing thread.
2017-03-06T16:11:16,073 [pool-9-thread-1] ERROR [InboundEventSource] Event Source (inputdata) state transitioned to ERROR.
com.sitewhere.spi.ServerStartupException
        at com.sitewhere.server.lifecycle.LifecycleComponent.startNestedComponent(LifecycleComponent.java:216) ~[sitewhere-core-1.9.0.jar!/:?]
        at com.sitewhere.server.lifecycle.TenantLifecycleComponent.startNestedComponent(TenantLifecycleComponent.java:60) ~[sitewhere-core-1.9.0.jar!/:?]
        at com.sitewhere.server.lifecycle.LifecycleComponent.startNestedComponent(LifecycleComponent.java:199) ~[sitewhere-core-1.9.0.jar!/:?]
        at com.sitewhere.device.communication.InboundEventSource.startEventReceivers(InboundEventSource.java:127) ~[sitewhere-core-1.9.0.jar!/:?]
        at com.sitewhere.device.communication.InboundEventSource.start(InboundEventSource.java:93) ~[sitewhere-core-1.9.0.jar!/:?]
        at com.sitewhere.server.lifecycle.LifecycleComponent.lifecycleStart(LifecycleComponent.java:164) [sitewhere-core-1.9.0.jar!/:?]
        at com.sitewhere.server.lifecycle.LifecycleComponent.startNestedComponent(LifecycleComponent.java:213) [sitewhere-core-1.9.0.jar!/:?]
        at com.sitewhere.server.lifecycle.TenantLifecycleComponent.startNestedComponent(TenantLifecycleComponent.java:60) [sitewhere-core-1.9.0.jar!/:?]
        at com.sitewhere.server.lifecycle.LifecycleComponent.startNestedComponent(LifecycleComponent.java:199) [sitewhere-core-1.9.0.jar!/:?]
        at com.sitewhere.device.communication.DeviceCommunication.start(DeviceCommunication.java:133) [sitewhere-core-1.9.0.jar!/:?]
        at com.sitewhere.server.lifecycle.LifecycleComponent.lifecycleStart(LifecycleComponent.java:164) [sitewhere-core-1.9.0.jar!/:?]
        at com.sitewhere.server.lifecycle.LifecycleComponent.startNestedComponent(LifecycleComponent.java:213) [sitewhere-core-1.9.0.jar!/:?]
        at com.sitewhere.server.lifecycle.TenantLifecycleComponent.startNestedComponent(TenantLifecycleComponent.java:60) [sitewhere-core-1.9.0.jar!/:?]
        at com.sitewhere.server.lifecycle.StartComponentLifecycleStep.execute(StartComponentLifecycleStep.java:36) [sitewhere-core-1.9.0.jar!/:?]
        at com.sitewhere.server.lifecycle.CompositeLifecycleStep.execute(CompositeLifecycleStep.java:69) [sitewhere-core-1.9.0.jar!/:?]
        at com.sitewhere.server.SiteWhereTenantEngine.start(SiteWhereTenantEngine.java:259) [sitewhere-core-1.9.0.jar!/:?]
        at com.sitewhere.server.lifecycle.LifecycleComponent.lifecycleStart(LifecycleComponent.java:164) [sitewhere-core-1.9.0.jar!/:?]
        at com.sitewhere.server.SiteWhereTenantEngine.lifecycleStart(SiteWhereTenantEngine.java:206) [sitewhere-core-1.9.0.jar!/:?]
        at com.sitewhere.server.tenant.SiteWhereTenantEngineCommands$StartCommand.call(SiteWhereTenantEngineCommands.java:89) [sitewhere-core-1.9.0.jar!/:?]
        at com.sitewhere.server.tenant.SiteWhereTenantEngineCommands$StartCommand.call(SiteWhereTenantEngineCommands.java:75) [sitewhere-core-1.9.0.jar!/:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
2017-03-06T16:11:16,073 [pool-9-thread-1] INFO  [DefaultDeviceCommunication] DefaultDeviceCommunication state transitioned to STARTED.
2017-03-06T16:11:16,075 [pool-9-thread-1] INFO  [SchedulerSignalerImpl] Initialized Scheduler Signaller of type: class org.quartz.core.SchedulerSignalerImpl
2017-03-06T16:11:16,075 [pool-9-thread-1] INFO  [QuartzScheduler] Quartz Scheduler v.2.2.3 created.
2017-03-06T16:11:16,075 [pool-9-thread-1] INFO  [RAMJobStore] RAMJobStore initialized.
2017-03-06T16:11:16,075 [pool-9-thread-1] INFO  [QuartzScheduler] Scheduler meta-data: Quartz Scheduler (v2.2.3) 'default' with instanceId 'sitewhere'
  Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 5 threads.
  Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.

2017-03-06T16:11:16,075 [pool-9-thread-1] INFO  [DirectSchedulerFactory] Quartz scheduler 'default
2017-03-06T16:11:16,075 [pool-9-thread-1] INFO  [DirectSchedulerFactory] Quartz scheduler version: 2.2.3
2017-03-06T16:11:16,075 [pool-9-thread-1] INFO  [QuartzScheduleManager] QuartzScheduleManager state transitioned to STARTING.
2017-03-06T16:11:16,075 [pool-9-thread-1] INFO  [QuartzScheduler] Scheduler default_$_sitewhere started.
2017-03-06T16:11:16,076 [pool-9-thread-1] INFO  [QuartzScheduleManager] Updated cache with 5 schedules.
2017-03-06T16:11:16,077 [pool-9-thread-1] INFO  [QuartzScheduleManager] QuartzScheduleManager state transitioned to STARTED.
2017-03-06T16:11:16,077 [pool-9-thread-1] INFO  [SiteWhereTenantEngine] Tenant already bootstrapped with tenant template data.
2017-03-06T16:11:16,077 [pool-9-thread-1] INFO  [SiteWhereTenantEngine] SiteWhereTenantEngine 'Default Tenant' (default) state transitioned to STARTED.
2017-03-06T16:11:16,078 [pool-2-thread-1] INFO  [FileSystemResourceManager] Created/updated resource: /opt/sitewhere/conf/tenants/default/tenant.state
2017-03-06T16:11:16,078 [pool-3-thread-1] INFO  [FileSystemResourceManager] Created/updated resource: /opt/sitewhere/conf/tenants/default/tenant.state
2017-03-06T16:11:16,078 [pool-2-thread-1] INFO  [FileSystemResourceManager] Created/updated resource: /opt/sitewhere/conf/tenants/default/tenant.state
2017-03-06T16:11:16,078 [pool-3-thread-1] INFO  [FileSystemResourceManager] Created/updated resource: /opt/sitewhere/conf/tenants/default/tenant.state
2017-03-06T16:11:16,079 [http-nio-8080-exec-1] INFO  [ResponseTimerFilter] Call for POST to 'http://data.agritech.vn:8080/sitewhere/api/tenants/default/engine/start' returned in 225 ms.
2017-03-06T16:11:16,760 [http-nio-8080-exec-8] INFO  [ResponseTimerFilter] Call for GET to 'http://data.agritech.vn:8080/sitewhere/api/tenants/templates' returned in 1 ms.
2017-03-06T16:11:16,777 [http-nio-8080-exec-5] INFO  [ResponseTimerFilter] Call for GET to 'http://data.agritech.vn:8080/sitewhere/api/users' returned in 3 ms.
2017-03-06T16:11:16,803 [http-nio-8080-exec-4] INFO  [ResponseTimerFilter] Call for GET to 'http://data.agritech.vn:8080/sitewhere/api/tenants/default' returned in 6 ms.
2017-03-06T16:11:16,865 [http-nio-8080-exec-7] INFO  [ResponseTimerFilter] Call for GET to 'http://data.agritech.vn:8080/sitewhere/api/tenants/default/engine/configuration/json' returned in 10 ms.

>

**Comment by supnobita** [comment]
Hi Derek,
Could you give me some advice ?

Thanks

**Comment by derekadams** [comment]
It's hard to tell what is breaking based on the log output. We have a number of requests for improving/documenting the socket event source for SiteWhere 1.10.0, so we will be taking a look as soon as we have time. It looks like there is a NullPointerException happening on startup with the socket event receiver, which means a bug in the initialization code. Based on the current backlog, it may be a while before we can debug the issue.
