### ISSUE TITLE
A serious error occurred during version 3.0.3 testing“All stream threads have died. The instance will be in error state and should be closed”

### ISSUE THREAD

**Issue by ATM006** [sitewhere/sitewhere#947]
1、-StreamThread-1] Encountered the following error during processing:: java.lang.NullPointerException
2、 All stream threads have died. The instance will be in error state and should be closed

2021-02-22 08:17:34,467 ERROR [org.apa.kaf.str.pro.int.StreamThread] (sitewhere-sitewhere-yinh-inbound-processing-decoded-15824e7f-7954-4473-8774-9c81159f4917-StreamThread-1) stream-thread [sitewhere-sitewhere-yinh-inbound-processing-decoded-15824e7f-7954-4473-8774-9c81159f4917-StreamThread-1] Encountered the following error during processing:: java.lang.NullPointerException
	at com.sitewhere.inbound.kafka.PreprocessedEventMapper.apply(PreprocessedEventMapper.java:80)
	at com.sitewhere.inbound.kafka.PreprocessedEventMapper.apply(PreprocessedEventMapper.java:30)
	at org.apache.kafka.streams.kstream.internals.KStreamMap$KStreamMapProcessor.process(KStreamMap.java:41)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.lambda$process$2(ProcessorNode.java:142)
	at org.apache.kafka.streams.processor.internals.metrics.StreamsMetricsImpl.maybeMeasureLatency(StreamsMetricsImpl.java:806)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:142)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:201)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:180)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:133)
	at org.apache.kafka.streams.kstream.internals.KStreamMap$KStreamMapProcessor.process(KStreamMap.java:42)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.lambda$process$2(ProcessorNode.java:142)
	at org.apache.kafka.streams.processor.internals.metrics.StreamsMetricsImpl.maybeMeasureLatency(StreamsMetricsImpl.java:806)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:142)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:201)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:180)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:133)
	at org.apache.kafka.streams.kstream.internals.PassThrough$PassThroughProcessor.process(PassThrough.java:33)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.lambda$process$2(ProcessorNode.java:142)
	at org.apache.kafka.streams.processor.internals.metrics.StreamsMetricsImpl.maybeMeasureLatency(StreamsMetricsImpl.java:806)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:142)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:201)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:188)
	at org.apache.kafka.streams.kstream.internals.KStreamBranch$KStreamBranchProcessor.process(KStreamBranch.java:48)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.lambda$process$2(ProcessorNode.java:142)
	at org.apache.kafka.streams.processor.internals.metrics.StreamsMetricsImpl.maybeMeasureLatency(StreamsMetricsImpl.java:806)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:142)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:201)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:180)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:133)
	at org.apache.kafka.streams.kstream.internals.KStreamMap$KStreamMapProcessor.process(KStreamMap.java:42)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.lambda$process$2(ProcessorNode.java:142)
	at org.apache.kafka.streams.processor.internals.metrics.StreamsMetricsImpl.maybeMeasureLatency(StreamsMetricsImpl.java:806)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:142)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:201)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:180)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:133)
	at org.apache.kafka.streams.processor.internals.SourceNode.process(SourceNode.java:101)
	at org.apache.kafka.streams.processor.internals.StreamTask.lambda$process$3(StreamTask.java:383)
	at org.apache.kafka.streams.processor.internals.metrics.StreamsMetricsImpl.maybeMeasureLatency(StreamsMetricsImpl.java:806)
	at org.apache.kafka.streams.processor.internals.StreamTask.process(StreamTask.java:383)
	at org.apache.kafka.streams.processor.internals.AssignedStreamsTasks.process(AssignedStreamsTasks.java:475)
	at org.apache.kafka.streams.processor.internals.TaskManager.process(TaskManager.java:550)
	at org.apache.kafka.streams.processor.internals.StreamThread.runOnce(StreamThread.java:802)
	at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:697)
	at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:670)

2021-02-22 08:17:34,468 INFO  [org.apa.kaf.str.pro.int.StreamThread] (sitewhere-sitewhere-yinh-inbound-processing-decoded-15824e7f-7954-4473-8774-9c81159f4917-StreamThread-1) stream-thread [sitewhere-sitewhere-yinh-inbound-processing-decoded-15824e7f-7954-4473-8774-9c81159f4917-StreamThread-1] State transition from RUNNING to PENDING_SHUTDOWN
2021-02-22 08:17:34,468 INFO  [org.apa.kaf.str.pro.int.StreamThread] (sitewhere-sitewhere-yinh-inbound-processing-decoded-15824e7f-7954-4473-8774-9c81159f4917-StreamThread-1) stream-thread [sitewhere-sitewhere-yinh-inbound-processing-decoded-15824e7f-7954-4473-8774-9c81159f4917-StreamThread-1] Shutting down
2021-02-22 08:17:34,474 INFO  [org.apa.kaf.cli.con.KafkaConsumer] (sitewhere-sitewhere-yinh-inbound-processing-decoded-15824e7f-7954-4473-8774-9c81159f4917-StreamThread-1) [Consumer clientId=sitewhere-sitewhere-yinh-inbound-processing-decoded-15824e7f-7954-4473-8774-9c81159f4917-StreamThread-1-restore-consumer, groupId=null] Unsubscribed all topics or patterns and assigned partitions
2021-02-22 08:17:34,475 INFO  [org.apa.kaf.cli.pro.KafkaProducer] (sitewhere-sitewhere-yinh-inbound-processing-decoded-15824e7f-7954-4473-8774-9c81159f4917-StreamThread-1) [Producer clientId=sitewhere-sitewhere-yinh-inbound-processing-decoded-15824e7f-7954-4473-8774-9c81159f4917-StreamThread-1-producer] Closing the Kafka producer with timeoutMillis = 9223372036854775807 ms.
2021-02-22 08:17:34,493 INFO  [org.apa.kaf.str.pro.int.StreamThread] (sitewhere-sitewhere-yinh-inbound-processing-decoded-15824e7f-7954-4473-8774-9c81159f4917-StreamThread-1) stream-thread [sitewhere-sitewhere-yinh-inbound-processing-decoded-15824e7f-7954-4473-8774-9c81159f4917-StreamThread-1] State transition from PENDING_SHUTDOWN to DEAD
2021-02-22 08:17:34,493 INFO  [org.apa.kaf.str.KafkaStreams] (sitewhere-sitewhere-yinh-inbound-processing-decoded-15824e7f-7954-4473-8774-9c81159f4917-StreamThread-1) stream-client [sitewhere-sitewhere-yinh-inbound-processing-decoded-15824e7f-7954-4473-8774-9c81159f4917] State transition from RUNNING to ERROR
2021-02-22 08:17:34,493 ERROR [org.apa.kaf.str.KafkaStreams] (sitewhere-sitewhere-yinh-inbound-processing-decoded-15824e7f-7954-4473-8774-9c81159f4917-StreamThread-1) stream-client [sitewhere-sitewhere-yinh-inbound-processing-decoded-15824e7f-7954-4473-8774-9c81159f4917] All stream threads have died. The instance will be in error state and should be closed.
2021-02-22 08:17:34,494 INFO  [org.apa.kaf.str.pro.int.StreamThread] (sitewhere-sitewhere-yinh-inbound-processing-decoded-15824e7f-7954-4473-8774-9c81159f4917-StreamThread-1) stream-thread [sitewhere-sitewhere-yinh-inbound-processing-decoded-15824e7f-7954-4473-8774-9c81159f4917-StreamThread-1] Shutdown complete
Exception in thread "sitewhere-sitewhere-yinh-inbound-processing-decoded-15824e7f-7954-4473-8774-9c81159f4917-StreamThread-1" java.lang.NullPointerException
	at com.sitewhere.inbound.kafka.PreprocessedEventMapper.apply(PreprocessedEventMapper.java:80)
	at com.sitewhere.inbound.kafka.PreprocessedEventMapper.apply(PreprocessedEventMapper.java:30)
	at org.apache.kafka.streams.kstream.internals.KStreamMap$KStreamMapProcessor.process(KStreamMap.java:41)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.lambda$process$2(ProcessorNode.java:142)
	at org.apache.kafka.streams.processor.internals.metrics.StreamsMetricsImpl.maybeMeasureLatency(StreamsMetricsImpl.java:806)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:142)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:201)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:180)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:133)
	at org.apache.kafka.streams.kstream.internals.KStreamMap$KStreamMapProcessor.process(KStreamMap.java:42)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.lambda$process$2(ProcessorNode.java:142)
	at org.apache.kafka.streams.processor.internals.metrics.StreamsMetricsImpl.maybeMeasureLatency(StreamsMetricsImpl.java:806)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:142)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:201)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:180)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:133)
	at org.apache.kafka.streams.kstream.internals.PassThrough$PassThroughProcessor.process(PassThrough.java:33)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.lambda$process$2(ProcessorNode.java:142)
	at org.apache.kafka.streams.processor.internals.metrics.StreamsMetricsImpl.maybeMeasureLatency(StreamsMetricsImpl.java:806)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:142)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:201)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:188)
	at org.apache.kafka.streams.kstream.internals.KStreamBranch$KStreamBranchProcessor.process(KStreamBranch.java:48)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.lambda$process$2(ProcessorNode.java:142)
	at org.apache.kafka.streams.processor.internals.metrics.StreamsMetricsImpl.maybeMeasureLatency(StreamsMetricsImpl.java:806)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:142)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:201)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:180)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:133)
	at org.apache.kafka.streams.kstream.internals.KStreamMap$KStreamMapProcessor.process(KStreamMap.java:42)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.lambda$process$2(ProcessorNode.java:142)
	at org.apache.kafka.streams.processor.internals.metrics.StreamsMetricsImpl.maybeMeasureLatency(StreamsMetricsImpl.java:806)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:142)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:201)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:180)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:133)
	at org.apache.kafka.streams.processor.internals.SourceNode.process(SourceNode.java:101)
	at org.apache.kafka.streams.processor.internals.StreamTask.lambda$process$3(StreamTask.java:383)
	at org.apache.kafka.streams.processor.internals.metrics.StreamsMetricsImpl.maybeMeasureLatency(StreamsMetricsImpl.java:806)
	at org.apache.kafka.streams.processor.internals.StreamTask.process(StreamTask.java:383)
	at org.apache.kafka.streams.processor.internals.AssignedStreamsTasks.process(AssignedStreamsTasks.java:475)
	at org.apache.kafka.streams.processor.internals.TaskManager.process(TaskManager.java:550)
	at org.apache.kafka.streams.processor.internals.StreamThread.runOnce(StreamThread.java:802)
	at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:697)
	at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:670)

**Comment by ATM006** [comment]
********************************************************************************
* Inbound Processing Microservice                                              *
* Microservice Version: 3.0.3.88fef65 (20210204233413)                         *
* Core Library Version: 3.0.5.944dad0 (20210204175938)                         *
*                                                                              *
* Git Revision: 88fef65d0f640898e38c53cf86f3a80215cf4083                       *
* Build Date: 20210204233413                                                   *
* Hostname: 10.244.20.153                                                      *
********************************************************************************

**Comment by derekadams** [comment]
It appears that our common Kafka Streams code isn't registering a handler for uncaught exceptions, so the `NullPointerException` is causing the pipeline to be killed. We will add the required exception handling code and put out a new release as soon as possible.

**Comment by yuyewuye** [comment]
When will the 3.0.5 release be?

**Comment by derekadams** [comment]
It will be soon. We have added the ability to build the debug images from the build process, but there are issues at runtime with the images and we are working on those before the release.

**Comment by yuyewuye** [comment]
Thanks ,Will #947 problem be closed?

**Comment by derekadams** [comment]
Yes, we have added an error handler which should prevent the Kafka Stream thread from stopping when exceptions occur.

**Comment by ATM006** [comment]
Has this bug been modified？

**Comment by ATM006** [comment]
It seems that this problem has not been [fixed](url)

********************************************************************************
* Inbound Processing Microservice                                              *
* Microservice Version: 3.0.5.a7ca898 (20210323205149)                         *
* Core Library Version: 3.0.11.29504be (20210323150236)                        *
*                                                                              *
* Git Revision: a7ca898667ab3c2778d13f8cbc0b9a2fb5656d15                       *
* Build Date: 20210323205149                                                   *                                                   *
********************************************************************************
[logs-from-inbound-processing-in-inbound-processing-f66dcff6-t4cz9.txt](https://github.com/sitewhere/sitewhere/files/6201733/logs-from-inbound-processing-in-inbound-processing-f66dcff6-t4cz9.txt)

**Comment by ATM006** [comment]
@derekadams It seems that this problem has not been fixed  

2021-03-28 04:30:30,987 INFO  [org.apa.kaf.str.pro.int.StreamThread] (sitewhere-sitewhere-autotest-inbound-processing-decoded-43ff51fe-43e1-46d7-bd2c-763cb57c86a9-StreamThread-1) stream-thread [sitewhere-sitewhere-autotest-inbound-processing-decoded-43ff51fe-43e1-46d7-bd2c-763cb57c86a9-StreamThread-1] State transition from RUNNING to PENDING_SHUTDOWN
2021-03-28 04:30:30,987 INFO  [org.apa.kaf.str.pro.int.StreamThread] (sitewhere-sitewhere-autotest-inbound-processing-decoded-43ff51fe-43e1-46d7-bd2c-763cb57c86a9-StreamThread-1) stream-thread [sitewhere-sitewhere-autotest-inbound-processing-decoded-43ff51fe-43e1-46d7-bd2c-763cb57c86a9-StreamThread-1] Shutting down
2021-03-28 04:30:31,001 INFO  [org.apa.kaf.cli.con.KafkaConsumer] (sitewhere-sitewhere-autotest-inbound-processing-decoded-43ff51fe-43e1-46d7-bd2c-763cb57c86a9-StreamThread-1) [Consumer clientId=sitewhere-sitewhere-autotest-inbound-processing-decoded-43ff51fe-43e1-46d7-bd2c-763cb57c86a9-StreamThread-1-restore-consumer, groupId=null] Unsubscribed all topics or patterns and assigned partitions
2021-03-28 04:30:31,001 INFO  [org.apa.kaf.cli.pro.KafkaProducer] (sitewhere-sitewhere-autotest-inbound-processing-decoded-43ff51fe-43e1-46d7-bd2c-763cb57c86a9-StreamThread-1) [Producer clientId=sitewhere-sitewhere-autotest-inbound-processing-decoded-43ff51fe-43e1-46d7-bd2c-763cb57c86a9-StreamThread-1-producer] Closing the Kafka producer with timeoutMillis = 9223372036854775807 ms.
2021-03-28 04:30:31,045 INFO  [org.apa.kaf.str.pro.int.StreamThread] (sitewhere-sitewhere-autotest-inbound-processing-decoded-43ff51fe-43e1-46d7-bd2c-763cb57c86a9-StreamThread-1) stream-thread [sitewhere-sitewhere-autotest-inbound-processing-decoded-43ff51fe-43e1-46d7-bd2c-763cb57c86a9-StreamThread-1] State transition from PENDING_SHUTDOWN to DEAD
2021-03-28 04:30:31,045 INFO  [org.apa.kaf.str.KafkaStreams] (sitewhere-sitewhere-autotest-inbound-processing-decoded-43ff51fe-43e1-46d7-bd2c-763cb57c86a9-StreamThread-1) stream-client [sitewhere-sitewhere-autotest-inbound-processing-decoded-43ff51fe-43e1-46d7-bd2c-763cb57c86a9] State transition from RUNNING to ERROR
2021-03-28 04:30:31,045 ERROR [org.apa.kaf.str.KafkaStreams] (sitewhere-sitewhere-autotest-inbound-processing-decoded-43ff51fe-43e1-46d7-bd2c-763cb57c86a9-StreamThread-1) stream-client [sitewhere-sitewhere-autotest-inbound-processing-decoded-43ff51fe-43e1-46d7-bd2c-763cb57c86a9] All stream threads have died. The instance will be in error state and should be closed.
2021-03-28 04:30:31,045 INFO  [org.apa.kaf.str.pro.int.StreamThread] (sitewhere-sitewhere-autotest-inbound-processing-decoded-43ff51fe-43e1-46d7-bd2c-763cb57c86a9-StreamThread-1) stream-thread [sitewhere-sitewhere-autotest-inbound-processing-decoded-43ff51fe-43e1-46d7-bd2c-763cb57c86a9-StreamThread-1] Shutdown complete
2021-03-28 04:30:31,047 WARN  [com.sit.inb.kaf.DecodedEventsPipeline] (sitewhere-sitewhere-autotest-inbound-processing-decoded-43ff51fe-43e1-46d7-bd2c-763cb57c86a9-StreamThread-1) Unhandled exception in Kafka Streams processing.: java.lang.NullPointerException
	at com.sitewhere.inbound.kafka.PreprocessedEventMapper.apply(PreprocessedEventMapper.java:90)
	at com.sitewhere.inbound.kafka.PreprocessedEventMapper.apply(PreprocessedEventMapper.java:39)
	at org.apache.kafka.streams.kstream.internals.KStreamMap$KStreamMapProcessor.process(KStreamMap.java:41)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.lambda$process$2(ProcessorNode.java:142)
	at org.apache.kafka.streams.processor.internals.metrics.StreamsMetricsImpl.maybeMeasureLatency(StreamsMetricsImpl.java:806)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:142)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:201)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:180)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:133)
	at org.apache.kafka.streams.kstream.internals.KStreamMap$KStreamMapProcessor.process(KStreamMap.java:42)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.lambda$process$2(ProcessorNode.java:142)
	at org.apache.kafka.streams.processor.internals.metrics.StreamsMetricsImpl.maybeMeasureLatency(StreamsMetricsImpl.java:806)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:142)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:201)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:180)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:133)
	at org.apache.kafka.streams.kstream.internals.PassThrough$PassThroughProcessor.process(PassThrough.java:33)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.lambda$process$2(ProcessorNode.java:142)
	at org.apache.kafka.streams.processor.internals.metrics.StreamsMetricsImpl.maybeMeasureLatency(StreamsMetricsImpl.java:806)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:142)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:201)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:188)
	at org.apache.kafka.streams.kstream.internals.KStreamBranch$KStreamBranchProcessor.process(KStreamBranch.java:48)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.lambda$process$2(ProcessorNode.java:142)
	at org.apache.kafka.streams.processor.internals.metrics.StreamsMetricsImpl.maybeMeasureLatency(StreamsMetricsImpl.java:806)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:142)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:201)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:180)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:133)
	at org.apache.kafka.streams.kstream.internals.KStreamMap$KStreamMapProcessor.process(KStreamMap.java:42)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.lambda$process$2(ProcessorNode.java:142)
	at org.apache.kafka.streams.processor.internals.metrics.StreamsMetricsImpl.maybeMeasureLatency(StreamsMetricsImpl.java:806)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:142)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:201)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:180)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:133)
	at org.apache.kafka.streams.processor.internals.SourceNode.process(SourceNode.java:101)
	at org.apache.kafka.streams.processor.internals.StreamTask.lambda$process$3(StreamTask.java:383)
	at org.apache.kafka.streams.processor.internals.metrics.StreamsMetricsImpl.maybeMeasureLatency(StreamsMetricsImpl.java:806)
	at org.apache.kafka.streams.processor.internals.StreamTask.process(StreamTask.java:383)
	at org.apache.kafka.streams.processor.internals.AssignedStreamsTasks.process(AssignedStreamsTasks.java:475)
	at org.apache.kafka.streams.processor.internals.TaskManager.process(TaskManager.java:550)
	at org.apache.kafka.streams.processor.internals.StreamThread.runOnce(StreamThread.java:802)
	at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:697)
	at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:670)
