### ISSUE TITLE
sitewhere-keycloak-0 error

### ISSUE THREAD

**Issue by ATM006** [sitewhere/sitewhere#960]
```
09:23:20,694 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-2) WFLYUT0008: Undertow HTTP listener default suspending
09:23:20,694 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-2) WFLYUT0007: Undertow HTTP listener default stopped, was bound to 0.0.0.0:8080
09:23:20,695 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-2) WFLYUT0004: Undertow 2.2.2.Final stopping
09:23:20,696 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 64) WFLYCLINF0003: Stopped http-remoting-connector cache from ejb container
09:23:20,700 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 66) WFLYCLINF0003: Stopped keys cache from keycloak container
09:23:20,701 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 69) WFLYCLINF0003: Stopped offlineSessions cache from keycloak container
09:23:20,701 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 67) WFLYCLINF0003: Stopped clientSessions cache from keycloak container
09:23:20,701 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 61) WFLYCLINF0003: Stopped offlineClientSessions cache from keycloak container
09:23:20,701 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-1) WFLYSRV0028: Stopped deployment keycloak-server.war (runtime-name: keycloak-server.war) in 432ms
09:23:20,701 INFO  [org.infinispan.manager.DefaultCacheManager] (ServerService Thread Pool -- 62) Stopping cache manager null on sitewhere-keycloak-0
09:23:20,702 INFO  [org.infinispan.CLUSTER] (ServerService Thread Pool -- 62) ISPN000080: Disconnecting JGroups channel ejb
09:23:20,704 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 65) WFLYCLINF0003: Stopped loginFailures cache from keycloak container
09:23:20,709 INFO  [org.infinispan.manager.DefaultCacheManager] (ServerService Thread Pool -- 65) Stopping cache manager null on sitewhere-keycloak-0
09:23:20,712 INFO  [org.infinispan.CLUSTER] (ServerService Thread Pool -- 65) ISPN000080: Disconnecting JGroups channel ejb
09:23:20,730 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("add") failed - address: ([("subsystem" => "microprofile-metrics-smallrye")]): java.lang.NullPointerException
	at org.wildfly.extension.microprofile.metrics-smallrye@21.0.2.Final//org.wildfly.extension.microprofile.metrics.MicroProfileMetricsSubsystemAdd$2.execute(MicroProfileMetricsSubsystemAdd.java:89)
	at org.jboss.as.controller@13.0.3.Final//org.jboss.as.controller.AbstractOperationContext.executeStep(AbstractOperationContext.java:1005)
	at org.jboss.as.controller@13.0.3.Final//org.jboss.as.controller.AbstractOperationContext.processStages(AbstractOperationContext.java:744)
	at org.jboss.as.controller@13.0.3.Final//org.jboss.as.controller.AbstractOperationContext.executeOperation(AbstractOperationContext.java:468)
	at org.jboss.as.controller@13.0.3.Final//org.jboss.as.controller.OperationContextImpl.executeOperation(OperationContextImpl.java:1415)
	at org.jboss.as.controller@13.0.3.Final//org.jboss.as.controller.ModelControllerImpl.boot(ModelControllerImpl.java:529)
	at org.jboss.as.controller@13.0.3.Final//org.jboss.as.controller.AbstractControllerService.boot(AbstractControllerService.java:515)
	at org.jboss.as.controller@13.0.3.Final//org.jboss.as.controller.AbstractControllerService.boot(AbstractControllerService.java:477)
	at org.jboss.as.server@13.0.3.Final//org.jboss.as.server.ServerService.boot(ServerService.java:451)
	at org.jboss.as.server@13.0.3.Final//org.jboss.as.server.ServerService.boot(ServerService.java:404)
	at org.jboss.as.controller@13.0.3.Final//org.jboss.as.controller.AbstractControllerService$1.run(AbstractControllerService.java:416)
	at java.base/java.lang.Thread.run(Thread.java:834)

09:23:20,739 ERROR [org.jboss.as.server] (ServerService Thread Pool -- 46) WFLYSRV0022: Deploy of deployment "keycloak-server.war" was rolled back with no failure message
09:23:20,769 INFO  [org.jboss.as] (MSC service thread 1-1) WFLYSRV0050: Keycloak 12.0.4 (WildFly Core 13.0.3.Final) stopped in 502ms```

**Comment by jorgevillaverde-sitewhere** [comment]
Hi @ATM006, this seems to be an error in Keycloak when it's starting. Can you provide the following infomation so that we try to reproduce the error?
- `swctl` version.
- Kuberentes version.
- Istio version.
- Steps to reproduce.

Thanks

**Comment by ATM006** [comment]
swctl：v0.9.2
Kuberentes:v1.18.8
istio:not enabled
sitewhere:v3.0.5

$:swctl install(Problems occur occasionally)

**Comment by jorgevillaverde-sitewhere** [comment]
Make sure you have Istio install in your cluster, it's [prerequisite](https://next.sitewhere.io/open-source/documentation/deployment-guide/swctl/#prerequistes) for installing SiteWhere. I'll try to reproduce the issue with Keycloak.

**Comment by derekadams** [comment]
Yes, it's probably best if you start with a clean installation. First, to completely clean your SiteWhere installation run:
```
swctl uninstall --purge
```
If you have ever installed Istio, run:
```
istioctl x uninstall --purge
```
..which will clear out any leftover Istio artifacts.
Now you can reinstall using:
```
istioctl install -y --set hub=gcr.io/istio-release
```
and finally
```
swctl install
```
If you are still having problems with Keycloak after that process, please comment here and we will continue to debug the issue.

**Comment by ATM006** [comment]
Thank you very much.  @jorgevillaverde-sitewhere @derekadams 

I didn't run "istioctl x uninstall --purge"，That should be the reason.
If there is a follow-up, I will come back to give feedback
