### ISSUE TITLE
I want Sitewhere to support other relational databases besides the default database postgres95. Can you give me some suggestions?

### ISSUE THREAD

**Issue by ATM006** [sitewhere/sitewhere#971]
I want Sitewhere to support other relational databases besides the default database postgres95. Can you give me some suggestions? I studied these codes：
https://github.com/sitewhere/sitewhere
https://github.com/sitewhere/sitewhere-k8s
https://github.com/sitewhere/sitewhere-microservice-core
https://github.com/sitewhere/sitewhere-k8s-model
There is a question. How does the ‘configurationTemplateId’ correspond to the destination database postgres95 when creating a tenant? I guess it is ‘files/configuration/instance/ict-default.yaml’, so how do I add my own template?

Request URL: http://127.0.0.1:30702/sitewhere/api/tenants
Request Method: POST
Status Code: 200 OK
Remote Address: 127.0.0.1:30702
Referrer Policy: no-referrer-when-downgrade
{token: "test", name: "test", authenticationToken: "test", authorizedUserIds: ["admin"],…}

**Comment by derekadams** [comment]
Adding a new database provider has a few steps:
* You have to add a provider to the RDB library as shown for PostgreSQL [here](https://github.com/sitewhere/sitewhere-integration/tree/master/sitewhere-rdb/src/main/java/com/sitewhere/rdb/providers).
* You would need to add the driver for the database [here](https://github.com/sitewhere/sitewhere-integration/blob/master/sitewhere-rdb/build.gradle#L16).
* If you want the database bootstrapped in the infrastructure, you would need to add the dependency to the infra Helm chart [here](https://github.com/sitewhere/sitewhere-k8s/blob/master/charts/sitewhere-infrastructure/Chart.yaml#L36).
* If you want to add a default global reference for the database, you would add that [here](https://github.com/sitewhere/sitewhere-k8s/blob/master/charts/sitewhere-infrastructure/files/configuration/instance/ict-default.yaml#L29). Note that these are Kubernetes resources, so you need to fork the chart or manually apply your updates via `kubectl apply`.
* If you want to have a separate tenant configuration dropdown choice that configures the database for tenants, you can create one like [this](https://github.com/sitewhere/sitewhere-k8s/blob/master/charts/sitewhere-infrastructure/files/configuration/tenant/tct-default.yaml) and then add references to the global like [this](https://github.com/sitewhere/sitewhere-k8s/blob/master/charts/sitewhere-infrastructure/files/configuration/tenant/default/tect-default-asset-management.yaml#L10).

Which database are you looking to support? We may be able to add it as part of the roadmap. Starting with SiteWhere `3.1.0` it will be a little harder to add providers since they will need to be compatible with Spring Native (GraalVM), which requires using a driver that can work with native images.

**Comment by ATM006** [comment]
Thank you for your answers. On the basis of open source software, I hope to add MYSQL. In addition, I hope to reserve extended interfaces for commercial databases (such as Oracle, etc.) and cloud databases to adapt to different scenarios.

-

**Comment by ATM006** [comment]
Another question, https://github.com/sitewhere/sitewhere-k8s does not have a release version of sitewhere3.0, and there is a conflict in the master branch.

https://github.com/sitewhere/sitewhere-k8s/blob/master/charts/sitewhere/Chart.yaml

**Comment by derekadams** [comment]
The `sitewhere` chart has been replaced by the `swctl` utility which handles deployment of the microservices. The only Helm chart still in use for the open source is `sitewhere-infrastructure` which is used in `swctl install` to install/parameterize the infrastructure.

**Comment by ATM006** [comment]
According to the above, we have encountered a problem:
How can I get the database type (PostgreSQL or others) in the tenant configuration after the function of createasset is entered

https://github.com/sitewhere/sitewhere/blob/a7ca898667ab3c2778d13f8cbc0b9a2fb5656d15/service-asset-management/src/main/java/com/sitewhere/asset/persistence/rdb/RdbAssetManagement.java#L60

**Comment by derekadams** [comment]
In general, we try to keep provider-specific logic out of the service interfaces. Since we use JPA, most relational databases should work with no changes to the service logic. If you _have_ to look at the provider information, you can use `getTenantEngine()` cast it to `RdbTenantEngine` and then call `getProviderInformation()`.

**Comment by ATM006** [comment]
Thank you very much. According to your tips, I encountered a new problem: 
As the database DM I used is not in the database type list of flywaydb, do you have any suggestions for solutions?
(Caused by: org.flywaydb.core.api.FlywayException: Unsupported Database: DM DBMS 7.1)

2021-05-11 11:29:14,218 ERROR [com.sit.mic.mul.TenantEngineManager] (Tenant Ops 1) Unable to initialize tenant engine for 'lanyang-asset-management'.: com.sitewhere.spi.microservice.ServerStartupException: Unable to start 'RdbEntityManagerProvider'
	at com.sitewhere.microservice.lifecycle.LifecycleComponent.startNestedComponent(LifecycleComponent.java:328)
	at com.sitewhere.microservice.lifecycle.TenantEngineLifecycleComponent.startNestedComponent(TenantEngineLifecycleComponent.java:249)
	at com.sitewhere.microservice.lifecycle.StartComponentLifecycleStep.execute(StartComponentLifecycleStep.java:55)
	at com.sitewhere.microservice.lifecycle.CompositeLifecycleStep.execute(CompositeLifecycleStep.java:83)
	at com.sitewhere.rdb.RdbTenantEngine.tenantStart(RdbTenantEngine.java:106)
	at com.sitewhere.asset.microservice.AssetManagementTenantEngine.tenantStart(AssetManagementTenantEngine.java:151)
	at com.sitewhere.microservice.multitenant.MicroserviceTenantEngine.start(MicroserviceTenantEngine.java:316)
	at com.sitewhere.microservice.lifecycle.LifecycleComponent.lifecycleStart(LifecycleComponent.java:260)
	at com.sitewhere.microservice.multitenant.TenantEngineManager.startTenantEngine(TenantEngineManager.java:434)
	at com.sitewhere.microservice.multitenant.TenantEngineManager$TenantEngineStarter.runAsSystemUser(TenantEngineManager.java:545)
	at com.sitewhere.microservice.security.SystemUserRunnable.run(SystemUserRunnable.java:80)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.sitewhere.spi.SiteWhereException: org.flywaydb.core.api.FlywayException: Unsupported Database: DM DBMS 7.1
	at com.sitewhere.microservice.lifecycle.LifecycleComponent.lifecycleStart(LifecycleComponent.java:288)
	at com.sitewhere.microservice.lifecycle.LifecycleComponent.startNestedComponent(LifecycleComponent.java:324)
	... 13 more
Caused by: org.flywaydb.core.api.FlywayException: Unsupported Database: DM DBMS 7.1
	at org.flywaydb.core.internal.jdbc.DatabaseType.fromDatabaseProductNameAndVersion(DatabaseType.java:146)
	at org.flywaydb.core.internal.jdbc.DatabaseType.fromJdbcConnection(DatabaseType.java:71)
	at org.flywaydb.core.internal.jdbc.JdbcConnectionFactory.<init>(JdbcConnectionFactory.java:82)
	at org.flywaydb.core.Flyway.execute(Flyway.java:453)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:158)
	at com.sitewhere.rdb.FlywayConfig.migrateTenantData(FlywayConfig.java:47)
	at com.sitewhere.rdb.RdbEntityManagerProvider.start(RdbEntityManagerProvider.java:125)
	at com.sitewhere.microservice.lifecycle.LifecycleComponent.lifecycleStart(LifecycleComponent.java:260)
	... 14 more

2021-05-11 11:29:14,219 WARN  [com.sit.mic.mul.TenantEngineManager] (Tenant Ops 1) Exception starting tenant engine.: com.sitewhere.spi.SiteWhereException: com.sitewhere.spi.microservice.ServerStartupException: Unable to start 'RdbEntityManagerProvider'
	at com.sitewhere.microservice.multitenant.TenantEngineManager.startTenantEngine(TenantEngineManager.java:447)
	at com.sitewhere.microservice.multitenant.TenantEngineManager$TenantEngineStarter.runAsSystemUser(TenantEngineManager.java:545)
	at com.sitewhere.microservice.security.SystemUserRunnable.run(SystemUserRunnable.java:80)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.sitewhere.spi.microservice.ServerStartupException: Unable to start 'RdbEntityManagerProvider'
	at com.sitewhere.microservice.lifecycle.LifecycleComponent.startNestedComponent(LifecycleComponent.java:328)
	at com.sitewhere.microservice.lifecycle.TenantEngineLifecycleComponent.startNestedComponent(TenantEngineLifecycleComponent.java:249)
	at com.sitewhere.microservice.lifecycle.StartComponentLifecycleStep.execute(StartComponentLifecycleStep.java:55)
	at com.sitewhere.microservice.lifecycle.CompositeLifecycleStep.execute(CompositeLifecycleStep.java:83)
	at com.sitewhere.rdb.RdbTenantEngine.tenantStart(RdbTenantEngine.java:106)
	at com.sitewhere.asset.microservice.AssetManagementTenantEngine.tenantStart(AssetManagementTenantEngine.java:151)
	at com.sitewhere.microservice.multitenant.MicroserviceTenantEngine.start(MicroserviceTenantEngine.java:316)
	at com.sitewhere.microservice.lifecycle.LifecycleComponent.lifecycleStart(LifecycleComponent.java:260)
	at com.sitewhere.microservice.multitenant.TenantEngineManager.startTenantEngine(TenantEngineManager.java:434)
	... 5 more
Caused by: com.sitewhere.spi.SiteWhereException: org.flywaydb.core.api.FlywayException: Unsupported Database: DM DBMS 7.1
	at com.sitewhere.microservice.lifecycle.LifecycleComponent.lifecycleStart(LifecycleComponent.java:288)
	at com.sitewhere.microservice.lifecycle.LifecycleComponent.startNestedComponent(LifecycleComponent.java:324)
	... 13 more
Caused by: org.flywaydb.core.api.FlywayException: Unsupported Database: DM DBMS 7.1
	at org.flywaydb.core.internal.jdbc.DatabaseType.fromDatabaseProductNameAndVersion(DatabaseType.java:146)
	at org.flywaydb.core.internal.jdbc.DatabaseType.fromJdbcConnection(DatabaseType.java:71)
	at org.flywaydb.core.internal.jdbc.JdbcConnectionFactory.<init>(JdbcConnectionFactory.java:82)
	at org.flywaydb.core.Flyway.execute(Flyway.java:453)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:158)
	at com.sitewhere.rdb.FlywayConfig.migrateTenantData(FlywayConfig.java:47)
	at com.sitewhere.rdb.RdbEntityManagerProvider.start(RdbEntityManagerProvider.java:125)
	at com.sitewhere.microservice.lifecycle.LifecycleComponent.lifecycleStart(LifecycleComponent.java:260)
	... 14 more
